const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context={window:{}};vm.runInNewContext(fs.readFileSync('payroll-matrix.js','utf8'),context);const m=context.window.PayrollMatrix;
test('monthly bonus independent of activity and real km basis',()=>{const r=m.calculate({bonuses:[{name:'Mensual',amount:'280.000'}]}, {},123);assert.equal(r.km,123);assert.equal(r.bonus,280000);assert.equal(r.commission,0);});
test('billed km and independent fixed/percentage commissions',()=>{const r=m.calculate({km_basis:'billed',commissions:[{concept_id:'battery',source:'extras',mode:'fixed',value:2000},{concept_id:'tow',source:'invoices',mode:'percent',value:10}]},{invoices:[{id:'i',concept_id:'tow',km:50.5,amount:50000,currency:'ARS',quantity:1}],extras:[{id:'e',concept_id:'battery',quantity:2}]},999);assert.equal(r.km,50.5);assert.equal(r.snapshot.km_records.join(','),'i');assert.equal(r.commission,9000);assert.equal(r.snapshot.commission_details[0].records[0],'e');});
test('real km uses journey odometers and billed km uses only valid invoice distances',()=>{assert.equal(m.calculate({km_basis:'real'},{invoices:[{id:'i',km:50}]},999).km,999);assert.equal(m.calculate({km_basis:'billed'},{invoices:[{id:'i',km:null}]},999).km,0);});
test('pay concepts are independently configurable',()=>{const matrix=m.normalize({pay_km:false,pay_services:false,pay_presentismo:false});assert.equal(matrix.pay_km,false);assert.equal(matrix.pay_services,false);assert.equal(matrix.pay_presentismo,false);});
test('invalid commissions do not generate misleading amounts',()=>{assert.throws(()=>m.normalize({commissions:[{concept_id:'a',source:'extras',mode:'percent',value:101}]}),/100/);assert.throws(()=>m.calculate({commissions:[{concept_id:'a',source:'extras',mode:'percent',value:10}]},{extras:[{concept_id:'a',amount:100,currency:'USD'}]},0),/ARS/);});
test('receipt escapes user-supplied bonus labels',()=>{assert.match(m.receiptHtml({compensation_snapshot:{km_basis:'real',bonuses:[{name:'<script>',amount:1}]}}),/&lt;script&gt;/);});

test('journey odometers define payable kilometers',()=>{assert.equal(m.journeyKm({status:'closed',km_inicio:1000,km_final:1180}),180);assert.equal(m.journeyKm({status:'open',km_inicio:1000}),null);assert.throws(()=>m.journeyKm({status:'closed',km_inicio:1000,km_final:900}),/odómetros/);assert.throws(()=>m.journeyKm({status:'closed',km_inicio:null,km_final:900}),/odómetros/);});
test('same sale source id is paid only once',()=>{const rule={commissions:[{concept_id:'battery',source:'extras',mode:'percent',value:10}]};const sale={id:'sale1',concept_id:'battery',amount:150000,currency:'ARS',quantity:1};assert.equal(m.calculate(rule,{extras:[sale,sale]},0).commission,15000);});
