const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {PGlite}=require('@electric-sql/pglite');
const service='20000000-0000-4000-8000-000000000001',report='30000000-0000-4000-8000-000000000001';
const migration=fs.readFileSync('supabase/migrations/20260924112634_service_review_report_v1.sql','utf8');
test('activados cerrados salen de Activos y Arribados, conservando Historial',()=>{
 const window={};const document={readyState:'loading',addEventListener(){}};
 vm.runInNewContext(fs.readFileSync('operator-services.js','utf8'),{window,document,console});
 const O=window.OperatorServices;
 O.S.services=[{service_id:'open',driver_activated:true,status:'at_origin'},{service_id:'bill',driver_activated:true,status:'completed',activation_billing:'billable'},{service_id:'no-bill',driver_activated:true,status:'completed',activation_billing:'non_billable'},{service_id:'cancel',driver_activated:true,status:'cancelled'},{service_id:'arrival',status:'at_origin'}];
 assert.deepEqual(Array.from(O.activeServices(),s=>s.service_id),['open','arrival']);
 assert.deepEqual(Array.from(O.historyServices(),s=>s.service_id),['bill','no-bill','cancel']);
 O.S.status='at_origin';assert.deepEqual(Array.from(O.filtered(),s=>s.service_id),['arrival']);
 O.S.status='activated';assert.deepEqual(Array.from(O.filtered(),s=>s.service_id),['open']);
 O.S.view='history';O.S.status='completed';assert.deepEqual(Array.from(O.filtered(),s=>s.service_id),['bill','no-bill']);
});
test('la ficha de un activado presenta responsables, motivo y destino sin pedir una firma',()=>{
 const wizard={serviceId:service,mode:'view',data:{},serviceSnapshot:{driver_activated:true,status:'at_origin',driver_name:'Chofer QA',truck_label:'Móvil 12',cancellation_reason_code:'provider',cancellation_reason_detail:'<Motivo>'}};
 const window={OperatorServices:{S:{wizard}},addEventListener(){}},document={addEventListener(){},querySelector:()=>null};
 vm.runInNewContext(fs.readFileSync('operator-service-commercial-addons-v1.js','utf8'),{window,document,setTimeout(){},console});
 const card=()=>window.OperatorServiceCommercialAddonsV1.activationCard();
 for(const text of ['Servicio activado','Chofer QA','Móvil 12','Pendiente de cierre administrativo','&lt;Motivo&gt;'])assert.ok(card().includes(text),text);
 assert.doesNotMatch(card(),/firmar|Pendiente de firma/);
 Object.assign(wizard.serviceSnapshot,{status:'completed',activation_billing:'non_billable',activation_billing_reason:'Convenio sin cargo'});
 assert.match(card(),/No facturable · Guardado en Historial/);assert.match(card(),/Convenio sin cargo/);assert.doesNotMatch(card(),/Finalizar activado/);
 wizard.serviceSnapshot.activation_billing='billable';assert.match(card(),/Enviado a Facturación/);
});
test('Postgres: informe recupera borradores, prioriza el cierre y controla permisos',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec(fs.readFileSync('test/fixtures/driver-handoff-schema.sql','utf8'));
 await db.exec(`create table operator_service_document_addon_reviews(review_line_id uuid default gen_random_uuid(),service_id uuid,remito_id integer,toll_report_id uuid,excess_report_id uuid,decision text,reason text,reviewed_at timestamptz default now());`);
 const fn=migration.match(/create or replace function public.get_operator_service_charge_review_report_v1[\s\S]*?end; \$\$;/i)[0];await db.exec(fn);
 await db.query("insert into operator_services(service_id,status,remito_id) values($1,'at_origin',1)",[service]);
 const read=async()=> (await db.query('select get_operator_service_charge_review_report_v1($1) as report',[service])).rows[0].report;
 await assert.rejects(read(),/Sin permiso/);
 await db.exec("select set_config('test.uid','10000000-0000-4000-8000-000000000001',false),set_config('test.role','operador',false)");
 await db.query("insert into operator_service_events(service_id,event_type,notes,details,created_at) values($1,'remito_review_pending','Consultar',{0}::jsonb,now()-interval '2 minutes')".replace('{0}','$2'),[service,JSON.stringify({decisions:{['toll:'+report]:{value:'rejected',reason:'Duplicado'}}})]);
 assert.equal((await read()).decisions['toll:'+report].saved,true);
 await db.query("insert into operator_service_document_addon_reviews(service_id,remito_id,toll_report_id,decision) values($1,1,$2,'accepted')",[service,report]);
 await db.query("update operator_services set status='completed' where service_id=$1",[service]);
 assert.equal((await read()).decisions['toll:'+report].value,'accepted');assert.equal((await read()).note,'');
 await db.exec("select set_config('test.role','supervision',false)");assert.equal((await read()).decisions['toll:'+report].saved,true);
 await db.exec("select set_config('test.role','chofer',false)");await assert.rejects(read(),/Sin permiso/);
 await db.exec("select set_config('test.role','operador',false)");
 await db.query("update operator_services set status='at_origin',remito_id=2 where service_id=$1",[service]);
 await db.query("insert into operator_service_events(service_id,event_type) values($1,'driver_remito_corrected')",[service]);
 assert.deepEqual((await read()).decisions,{});
});
