/* AuxiliOS · Fase 1: empresas, contactos y sucursales */
(() => {
  'use strict';
  const S = { companies: [], selected: null, contacts: [], branches: [], editCompany: null, editContact: null, editBranch: null };
  const role = () => typeof PERFIL_USUARIO === 'undefined' ? '' : (PERFIL_USUARIO?.roles?.name || PERFIL_USUARIO?.role || '');
  const canRead = () => ['administracion', 'supervision'].includes(role());
  const canWrite = () => role() === 'administracion';
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean = v => String(v ?? '').trim() || null;
  const digits = v => String(v || '').replace(/\D/g, '');
  const cuitFmt = v => { const d = digits(v); return d.length === 11 ? `${d.slice(0,2)}-${d.slice(2,10)}-${d.slice(10)}` : (v || '—'); };
  const notify = (m,t='info') => typeof toast === 'function' ? toast(m,t) : console.log(m);
  const open = id => typeof openModal === 'function' ? openModal(id) : document.getElementById(id)?.classList.add('open');
  const close = id => typeof closeModal === 'function' ? closeModal(id) : document.getElementById(id)?.classList.remove('open');
  const status = v => ({active:'Activa',suspended:'Suspendida',inactive:'Inactiva'}[v] || v);
  const current = () => S.companies.find(x => x.company_id === S.selected);

  function inject() {
    if (document.getElementById('screen-empresas')) return;
    document.head.insertAdjacentHTML('beforeend', `<style id="emp-css">
      #screen-empresas{padding-bottom:40px}.emp-head,.emp-tools,.emp-detail-head,.emp-section-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.emp-head{margin-bottom:14px}.emp-head h2{margin:0;font:28px 'Bebas Neue'}.emp-sub{font-size:11px;color:var(--muted)}.emp-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.emp-kpi,.emp-box,.emp-mini{background:var(--panel);border:1px solid var(--border);border-radius:10px}.emp-kpi{padding:12px}.emp-kpi b{display:block;font:21px 'DM Mono';margin-top:4px}.emp-tools{margin-bottom:12px}.emp-tools input{flex:1}.emp-layout{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(420px,1.5fr);gap:12px}.emp-list{max-height:650px;overflow:auto}.emp-row{padding:12px;border-bottom:1px solid var(--border);cursor:pointer}.emp-row:hover,.emp-row.active{background:var(--amber-lo)}.emp-row.active{border-left:3px solid var(--amber)}.emp-row-top{display:flex;justify-content:space-between;gap:8px}.emp-name{font-size:13px;font-weight:700}.emp-meta{font-size:10px;color:var(--muted);margin-top:5px}.emp-badge{font-size:9px;border:1px solid var(--border);border-radius:99px;padding:3px 7px}.emp-detail{padding:16px}.emp-detail h3{margin:0;font:25px 'Bebas Neue'}.emp-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.emp-mini{padding:10px;background:var(--bg)}.emp-mini small{display:block;color:var(--muted);text-transform:uppercase;font-size:9px}.emp-mini div{font-size:11px;margin-top:4px;overflow-wrap:anywhere}.emp-section{margin-top:16px}.emp-cards{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:8px}.emp-card{padding:10px;background:var(--bg);border:1px solid var(--border);border-radius:8px}.emp-card b{font-size:12px}.emp-lines{font-size:10px;color:var(--muted2);display:grid;gap:3px;margin-top:6px}.emp-actions{display:flex;gap:5px;margin-top:8px;flex-wrap:wrap}.emp-empty{padding:30px;text-align:center;color:var(--muted)}.emp-modal{width:min(720px,calc(100vw - 24px));max-width:720px}.emp-check{display:flex;gap:8px;align-items:center;font-size:12px;margin:8px 0}.emp-readonly{padding:8px 10px;border:1px solid rgba(77,161,255,.3);border-radius:8px;color:var(--blue);font-size:11px;margin-bottom:10px}@media(max-width:900px){.emp-layout{grid-template-columns:1fr}.emp-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.emp-head,.emp-tools,.emp-detail-head{align-items:stretch;flex-direction:column}.emp-kpis,.emp-grid,.emp-cards{grid-template-columns:1fr 1fr}.emp-tools select{width:100%}}@media(max-width:430px){.emp-kpis,.emp-grid,.emp-cards{grid-template-columns:1fr}}
    </style>`);
    const bottom = document.querySelector('.sidenav .nav-bottom');
    bottom?.insertAdjacentHTML('beforebegin', `<div class="nav-item" id="nav-empresas" onclick="goTo('empresas')" style="display:none"><span class="nav-icon">🏢</span><span class="nav-label">Empresas</span></div>`);
    document.querySelector('.content')?.insertAdjacentHTML('beforeend', `<div class="screen" id="screen-empresas">
      <div class="emp-head"><div><h2>Empresas</h2><div class="emp-sub">Clientes corporativos, contactos y sucursales</div></div><button class="btn btn-primary emp-write" onclick="abrirEmpresa()">＋ Nueva empresa</button></div>
      <div id="emp-ro" class="emp-readonly" style="display:none">Supervisión tiene acceso de consulta. Las modificaciones corresponden a Administración.</div>
      <div class="emp-kpis"><div class="emp-kpi"><small>Total</small><b id="emp-total">0</b></div><div class="emp-kpi"><small>Activas</small><b id="emp-active">0</b></div><div class="emp-kpi"><small>Suspendidas</small><b id="emp-suspended">0</b></div><div class="emp-kpi"><small>Inactivas</small><b id="emp-inactive">0</b></div></div>
      <div class="emp-tools"><input class="form-input" id="emp-q" placeholder="Buscar empresa, código o CUIT" oninput="renderEmpresas()"><select class="form-input" id="emp-filter" onchange="renderEmpresas()"><option value="all">Todos los estados</option><option value="active">Activas</option><option value="suspended">Suspendidas</option><option value="inactive">Inactivas</option></select><button class="btn btn-ghost" onclick="cargarEmpresas()">↻</button></div>
      <div class="emp-layout"><div class="emp-box"><div class="emp-list" id="emp-list"><div class="emp-empty">Cargando…</div></div></div><div class="emp-box" id="emp-detail"><div class="emp-empty">Seleccioná una empresa.</div></div></div>
    </div>`);
    document.body.insertAdjacentHTML('beforeend', modals());
  }

  function modals() { return `<div class="modal-backdrop" id="modal-empresa"><div class="modal-box emp-modal"><div class="modal-head"><span class="modal-head-title" id="ec-title">Nueva empresa</span><button class="modal-close" onclick="closeModal('modal-empresa')">×</button></div><div class="modal-body">
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Razón social *</label><input class="form-input" id="ec-legal"></div><div class="form-group"><label class="form-label">Nombre comercial</label><input class="form-input" id="ec-trade"></div></div>
    <div class="form-grid-2"><div class="form-group"><label class="form-label">CUIT</label><input class="form-input" id="ec-cuit" inputmode="numeric"></div><div class="form-group"><label class="form-label">Estado</label><select class="form-input" id="ec-status"><option value="active">Activa</option><option value="suspended">Suspendida</option><option value="inactive">Inactiva</option></select></div></div>
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Teléfono</label><input class="form-input" id="ec-phone"></div><div class="form-group"><label class="form-label">WhatsApp</label><input class="form-input" id="ec-wa"></div></div>
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Email operativo</label><input class="form-input" id="ec-op" type="email"></div><div class="form-group"><label class="form-label">Email facturación</label><input class="form-input" id="ec-bill" type="email"></div></div>
    <div class="form-group"><label class="form-label">Condición de pago (días)</label><input class="form-input" id="ec-days" type="number" min="0" max="365" value="30"></div><div class="form-group"><label class="form-label">Observaciones</label><textarea class="form-input" id="ec-notes"></textarea></div><div class="modal-error" id="ec-error" style="display:none"></div>
    </div><div class="modal-footer"><button class="btn btn-ghost" onclick="closeModal('modal-empresa')">Cancelar</button><button class="btn btn-primary" onclick="guardarEmpresa()">Guardar</button></div></div></div>
    <div class="modal-backdrop" id="modal-emp-contact"><div class="modal-box"><div class="modal-head"><span class="modal-head-title" id="ct-title">Nuevo contacto</span><button class="modal-close" onclick="closeModal('modal-emp-contact')">×</button></div><div class="modal-body">
    <div class="form-group"><label class="form-label">Nombre *</label><input class="form-input" id="ct-name"></div><div class="form-grid-2"><div class="form-group"><label class="form-label">Cargo</label><input class="form-input" id="ct-job"></div><div class="form-group"><label class="form-label">Tipo</label><select class="form-input" id="ct-type"><option value="operativo">Operativo</option><option value="facturacion">Facturación</option><option value="comercial">Comercial</option><option value="otro">Otro</option></select></div></div>
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Teléfono</label><input class="form-input" id="ct-phone"></div><div class="form-group"><label class="form-label">WhatsApp</label><input class="form-input" id="ct-wa"></div></div><div class="form-group"><label class="form-label">Email</label><input class="form-input" id="ct-email" type="email"></div><label class="emp-check"><input id="ct-primary" type="checkbox"> Contacto principal</label><div class="form-group"><label class="form-label">Notas</label><textarea class="form-input" id="ct-notes"></textarea></div><div class="modal-error" id="ct-error" style="display:none"></div>
    </div><div class="modal-footer"><button class="btn btn-ghost" onclick="closeModal('modal-emp-contact')">Cancelar</button><button class="btn btn-primary" onclick="guardarContacto()">Guardar</button></div></div></div>
    <div class="modal-backdrop" id="modal-emp-branch"><div class="modal-box emp-modal"><div class="modal-head"><span class="modal-head-title" id="br-title">Nueva sucursal</span><button class="modal-close" onclick="closeModal('modal-emp-branch')">×</button></div><div class="modal-body">
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Nombre *</label><input class="form-input" id="br-name"></div><div class="form-group"><label class="form-label">Código</label><input class="form-input" id="br-code"></div></div><div class="form-group"><label class="form-label">Dirección *</label><input class="form-input" id="br-address"></div>
    <div class="form-grid-2"><div class="form-group"><label class="form-label">Localidad</label><input class="form-input" id="br-city"></div><div class="form-group"><label class="form-label">Provincia</label><input class="form-input" id="br-province" value="Buenos Aires"></div></div><div class="form-grid-2"><div class="form-group"><label class="form-label">Código postal</label><input class="form-input" id="br-postal"></div><div class="form-group"><label class="form-label">Teléfono</label><input class="form-input" id="br-phone"></div></div><div class="form-group"><label class="form-label">Email operativo</label><input class="form-input" id="br-email" type="email"></div><div class="form-grid-2"><div class="form-group"><label class="form-label">Latitud</label><input class="form-input" id="br-lat"></div><div class="form-group"><label class="form-label">Longitud</label><input class="form-input" id="br-lng"></div></div><div class="form-group"><label class="form-label">Horarios</label><input class="form-input" id="br-hours"></div><label class="emp-check"><input id="br-primary" type="checkbox"> Sucursal principal</label><div class="form-group"><label class="form-label">Notas</label><textarea class="form-input" id="br-notes"></textarea></div><div class="modal-error" id="br-error" style="display:none"></div>
    </div><div class="modal-footer"><button class="btn btn-ghost" onclick="closeModal('modal-emp-branch')">Cancelar</button><button class="btn btn-primary" onclick="guardarSucursal()">Guardar</button></div></div></div>`; }

  function applyRole() {
    const nav = document.getElementById('nav-empresas'); if (nav) nav.style.display = canRead() ? '' : 'none';
    document.querySelectorAll('.emp-write').forEach(x => x.style.display = canWrite() ? '' : 'none');
    const ro = document.getElementById('emp-ro'); if (ro) ro.style.display = canRead() && !canWrite() ? '' : 'none';
  }

  async function cargar() {
    if (!canRead()) return notify('Sin permiso para consultar empresas','error');
    const {data,error} = await _db.from('companies').select('*').order('legal_name');
    if (error) return notify('No se pudieron cargar las empresas','error');
    S.companies = data || []; if (S.selected && !S.companies.some(x => x.company_id === S.selected)) S.selected = null;
    ['total','active','suspended','inactive'].forEach(k => { const el=document.getElementById(`emp-${k}`); if(el) el.textContent = k==='total' ? S.companies.length : S.companies.filter(x=>x.status===k).length; });
    render(); applyRole(); if (S.selected) await selectCompany(S.selected,false);
  }

  function render() {
    const q=(document.getElementById('emp-q')?.value||'').toLowerCase().trim(), f=document.getElementById('emp-filter')?.value||'all';
    const rows=S.companies.filter(x=>(f==='all'||x.status===f)&&(!q||`${x.company_code} ${x.legal_name} ${x.trade_name||''} ${x.cuit||''}`.toLowerCase().includes(q)));
    const el=document.getElementById('emp-list'); if(!el) return;
    el.innerHTML=rows.length?rows.map(x=>`<div class="emp-row ${S.selected===x.company_id?'active':''}" onclick="seleccionarEmpresa('${x.company_id}')"><div class="emp-row-top"><div><div class="emp-name">${esc(x.legal_name)}</div><div class="emp-meta">${esc(x.trade_name||x.company_code)} · CUIT ${esc(cuitFmt(x.cuit))}</div></div><span class="emp-badge">${status(x.status)}</span></div></div>`).join(''):'<div class="emp-empty">Sin resultados.</div>';
  }

  async function selectCompany(id,re=true) {
    S.selected=id; if(re) render();
    const [c,b]=await Promise.all([_db.from('company_contacts').select('*').eq('company_id',id).order('is_primary',{ascending:false}).order('full_name'),_db.from('company_branches').select('*').eq('company_id',id).order('is_primary',{ascending:false}).order('name')]);
    S.contacts=c.data||[]; S.branches=b.data||[]; detail();
  }

  function detail() {
    const x=current(), el=document.getElementById('emp-detail'); if(!x||!el) return;
    const contacts=S.contacts.filter(i=>i.is_active), branches=S.branches.filter(i=>i.is_active);
    el.innerHTML=`<div class="emp-detail"><div class="emp-detail-head"><div><div class="emp-sub">${esc(x.company_code)} · ${status(x.status)}</div><h3>${esc(x.legal_name)}</h3><div class="emp-sub">${esc(x.trade_name||'Sin nombre comercial')}</div></div>${canWrite()?`<div><button class="btn btn-ghost" onclick="abrirEmpresa('${x.company_id}')">Editar</button> ${x.status!=='inactive'?`<button class="btn btn-ghost" onclick="desactivarEmpresa('${x.company_id}')">Desactivar</button>`:''}</div>`:''}</div>
      <div class="emp-grid">${info('CUIT',cuitFmt(x.cuit))}${info('Teléfono',x.phone)}${info('WhatsApp',x.whatsapp)}${info('Email operativo',x.operational_email)}${info('Email facturación',x.billing_email)}${info('Pago',Number(x.payment_terms_days||0)===0?'Contado':`${x.payment_terms_days} días`)}</div>
      ${x.notes?`<div class="emp-mini"><small>Observaciones</small><div>${esc(x.notes)}</div></div>`:''}
      <div class="emp-section"><div class="emp-section-head"><b>Contactos (${contacts.length})</b>${canWrite()?'<button class="btn btn-ghost" onclick="abrirContacto()">＋ Agregar</button>':''}</div><div class="emp-cards">${contacts.length?contacts.map(contactCard).join(''):'<div class="emp-empty">Sin contactos activos.</div>'}</div></div>
      <div class="emp-section"><div class="emp-section-head"><b>Sucursales (${branches.length})</b>${canWrite()?'<button class="btn btn-ghost" onclick="abrirSucursal()">＋ Agregar</button>':''}</div><div class="emp-cards">${branches.length?branches.map(branchCard).join(''):'<div class="emp-empty">Sin sucursales activas.</div>'}</div></div></div>`;
  }
  const info=(l,v)=>`<div class="emp-mini"><small>${l}</small><div>${esc(v||'—')}</div></div>`;
  const contactCard=c=>`<div class="emp-card"><b>${esc(c.full_name)}</b><div class="emp-sub">${esc(c.contact_type)}${c.is_primary?' · Principal':''}</div><div class="emp-lines">${c.job_title?`<span>${esc(c.job_title)}</span>`:''}${c.phone?`<span>☎ ${esc(c.phone)}</span>`:''}${c.whatsapp?`<span>WhatsApp ${esc(c.whatsapp)}</span>`:''}${c.email?`<span>✉ ${esc(c.email)}</span>`:''}</div>${canWrite()?`<div class="emp-actions"><button class="btn btn-ghost" onclick="abrirContacto('${c.contact_id}')">Editar</button><button class="btn btn-ghost" onclick="desactivarContacto('${c.contact_id}')">Desactivar</button></div>`:''}</div>`;
  const branchCard=b=>`<div class="emp-card"><b>${esc(b.name)}</b><div class="emp-sub">${esc(b.branch_code||'Sin código')}${b.is_primary?' · Principal':''}</div><div class="emp-lines"><span>📍 ${esc(b.address)}</span>${b.city||b.province?`<span>${esc([b.city,b.province].filter(Boolean).join(', '))}</span>`:''}${b.phone?`<span>☎ ${esc(b.phone)}</span>`:''}${b.schedule_notes?`<span>🕐 ${esc(b.schedule_notes)}</span>`:''}</div>${canWrite()?`<div class="emp-actions"><button class="btn btn-ghost" onclick="abrirSucursal('${b.branch_id}')">Editar</button><button class="btn btn-ghost" onclick="desactivarSucursal('${b.branch_id}')">Desactivar</button></div>`:''}</div>`;
  const setError=(id,m)=>{const e=document.getElementById(id);if(e){e.textContent=m?`⚠ ${m}`:'';e.style.display=m?'':'none';}};

  function abrirEmpresa(id=null) { if(!canWrite())return; S.editCompany=id; const x=S.companies.find(i=>i.company_id===id); document.getElementById('ec-title').textContent=x?'Editar empresa':'Nueva empresa'; [['ec-legal',x?.legal_name],['ec-trade',x?.trade_name],['ec-cuit',x?.cuit?cuitFmt(x.cuit):''],['ec-phone',x?.phone],['ec-wa',x?.whatsapp],['ec-op',x?.operational_email],['ec-bill',x?.billing_email],['ec-days',x?.payment_terms_days??30],['ec-notes',x?.notes]].forEach(([i,v])=>document.getElementById(i).value=v||''); document.getElementById('ec-status').value=x?.status||'active'; setError('ec-error',''); open('modal-empresa'); }
  async function guardarEmpresa() { const legal=document.getElementById('ec-legal').value.trim(), cuit=digits(document.getElementById('ec-cuit').value), days=Number(document.getElementById('ec-days').value||0); if(legal.length<2)return setError('ec-error','Ingresá una razón social válida.'); if(cuit&&cuit.length!==11)return setError('ec-error','El CUIT debe tener 11 dígitos.'); if(days<0||days>365)return setError('ec-error','La condición de pago no es válida.'); const p={legal_name:legal,trade_name:clean(document.getElementById('ec-trade').value),cuit:cuit||null,status:document.getElementById('ec-status').value,phone:clean(document.getElementById('ec-phone').value),whatsapp:clean(document.getElementById('ec-wa').value),operational_email:clean(document.getElementById('ec-op').value)?.toLowerCase()||null,billing_email:clean(document.getElementById('ec-bill').value)?.toLowerCase()||null,payment_terms_days:days,notes:clean(document.getElementById('ec-notes').value)}; const r=S.editCompany?await _db.from('companies').update(p).eq('company_id',S.editCompany).select().single():await _db.from('companies').insert(p).select().single(); if(r.error)return setError('ec-error',r.error.code==='23505'?'Ya existe una empresa con ese CUIT.':'No se pudo guardar.'); S.selected=r.data.company_id; close('modal-empresa'); notify('Empresa guardada','success'); await cargar(); }
  async function desactivarEmpresa(id){if(!canWrite()||!confirm('¿Desactivar esta empresa?'))return;const{error}=await _db.from('companies').update({status:'inactive'}).eq('company_id',id);if(error)return notify('No se pudo desactivar','error');await cargar();}

  function abrirContacto(id=null){if(!canWrite()||!S.selected)return;S.editContact=id;const x=S.contacts.find(i=>i.contact_id===id);document.getElementById('ct-title').textContent=x?'Editar contacto':'Nuevo contacto';[['ct-name',x?.full_name],['ct-job',x?.job_title],['ct-phone',x?.phone],['ct-wa',x?.whatsapp],['ct-email',x?.email],['ct-notes',x?.notes]].forEach(([i,v])=>document.getElementById(i).value=v||'');document.getElementById('ct-type').value=x?.contact_type||'operativo';document.getElementById('ct-primary').checked=!!x?.is_primary;setError('ct-error','');open('modal-emp-contact');}
  async function guardarContacto(){const name=document.getElementById('ct-name').value.trim(),phone=clean(document.getElementById('ct-phone').value),wa=clean(document.getElementById('ct-wa').value),email=clean(document.getElementById('ct-email').value)?.toLowerCase()||null,type=document.getElementById('ct-type').value,primary=document.getElementById('ct-primary').checked;if(name.length<2)return setError('ct-error','Ingresá el nombre.');if(!phone&&!wa&&!email)return setError('ct-error','Ingresá al menos un medio de contacto.');if(primary){let q=_db.from('company_contacts').update({is_primary:false}).eq('company_id',S.selected).eq('contact_type',type).eq('is_primary',true);if(S.editContact)q=q.neq('contact_id',S.editContact);const z=await q;if(z.error)return setError('ct-error','No se pudo cambiar el contacto principal.');}const p={company_id:S.selected,full_name:name,job_title:clean(document.getElementById('ct-job').value),contact_type:type,phone,whatsapp:wa,email,is_primary:primary,is_active:true,notes:clean(document.getElementById('ct-notes').value)};const r=S.editContact?await _db.from('company_contacts').update(p).eq('contact_id',S.editContact):await _db.from('company_contacts').insert(p);if(r.error)return setError('ct-error','No se pudo guardar.');close('modal-emp-contact');await selectCompany(S.selected,false);}
  async function desactivarContacto(id){if(!confirm('¿Desactivar este contacto?'))return;await _db.from('company_contacts').update({is_active:false,is_primary:false}).eq('contact_id',id);await selectCompany(S.selected,false);}

  function abrirSucursal(id=null){if(!canWrite()||!S.selected)return;S.editBranch=id;const x=S.branches.find(i=>i.branch_id===id);document.getElementById('br-title').textContent=x?'Editar sucursal':'Nueva sucursal';[['br-name',x?.name],['br-code',x?.branch_code],['br-address',x?.address],['br-city',x?.city],['br-province',x?.province||'Buenos Aires'],['br-postal',x?.postal_code],['br-phone',x?.phone],['br-email',x?.operational_email],['br-lat',x?.latitude],['br-lng',x?.longitude],['br-hours',x?.schedule_notes],['br-notes',x?.notes]].forEach(([i,v])=>document.getElementById(i).value=v??'');document.getElementById('br-primary').checked=!!x?.is_primary;setError('br-error','');open('modal-emp-branch');}
  async function guardarSucursal(){const name=document.getElementById('br-name').value.trim(),address=document.getElementById('br-address').value.trim(),primary=document.getElementById('br-primary').checked,lat=clean(document.getElementById('br-lat').value),lng=clean(document.getElementById('br-lng').value);if(name.length<2)return setError('br-error','Ingresá el nombre.');if(address.length<3)return setError('br-error','Ingresá la dirección.');if(primary){let q=_db.from('company_branches').update({is_primary:false}).eq('company_id',S.selected).eq('is_primary',true);if(S.editBranch)q=q.neq('branch_id',S.editBranch);const z=await q;if(z.error)return setError('br-error','No se pudo cambiar la sucursal principal.');}const p={company_id:S.selected,name,address,branch_code:clean(document.getElementById('br-code').value)?.toUpperCase()||null,city:clean(document.getElementById('br-city').value),province:clean(document.getElementById('br-province').value)||'Buenos Aires',postal_code:clean(document.getElementById('br-postal').value),phone:clean(document.getElementById('br-phone').value),operational_email:clean(document.getElementById('br-email').value)?.toLowerCase()||null,latitude:lat?Number(lat.replace(',','.')):null,longitude:lng?Number(lng.replace(',','.')):null,schedule_notes:clean(document.getElementById('br-hours').value),is_primary:primary,is_active:true,notes:clean(document.getElementById('br-notes').value)};const r=S.editBranch?await _db.from('company_branches').update(p).eq('branch_id',S.editBranch):await _db.from('company_branches').insert(p);if(r.error)return setError('br-error',r.error.code==='23505'?'Código duplicado o ya existe una sucursal principal.':'No se pudo guardar.');close('modal-emp-branch');await selectCompany(S.selected,false);}
  async function desactivarSucursal(id){if(!confirm('¿Desactivar esta sucursal?'))return;await _db.from('company_branches').update({is_active:false,is_primary:false}).eq('branch_id',id);await selectCompany(S.selected,false);}

  function init(){inject();if(typeof SCREENS!=='undefined')SCREENS.empresas={title:'EMPRESAS',sub:'Fase 1 · Empresas, contactos y sucursales'};if(typeof goTo==='function'&&!window.__empNav){const old=goTo;window.goTo=n=>{old(n);if(n==='empresas')cargar();};window.__empNav=true;}let n=0;const timer=setInterval(()=>{applyRole();if(role()||++n>40)clearInterval(timer);},250);}
  Object.assign(window,{cargarEmpresas:cargar,renderEmpresas:render,seleccionarEmpresa:selectCompany,abrirEmpresa,guardarEmpresa,desactivarEmpresa,abrirContacto,guardarContacto,desactivarContacto,abrirSucursal,guardarSucursal,desactivarSucursal});
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
