/* AuxiliOS · Facturación · mesa canónica v1 */
(()=>{'use strict';
const S={rows:[],kpis:{},tab:'pending',search:'',loading:false,detail:null,detailLoading:false,confirmReview:false,searchTimer:null};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const profile=()=>typeof PERFIL_USUARIO!=='undefined'?PERFIL_USUARIO:(window.PERFIL_USUARIO||{});
const role=()=>norm(profile()?.roles?.name||profile()?.role?.name||profile()?.role||profile()?.role_name||'');
const canRead=()=>['administracion','facturacion','supervision'].includes(role());
const canReview=()=>['administracion','facturacion'].includes(role());
const db=()=>typeof _db!=='undefined'?_db:null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const notify=(m,t='info')=>typeof window.toast==='function'?window.toast(m,t):console[t==='error'?'error':'log'](m);
const money=(v,c='ARS')=>new Intl.NumberFormat('es-AR',{style:'currency',currency:c||'ARS',maximumFractionDigits:2}).format(num(v));
const date=v=>v?new Date(v).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';

function injectAssets(){if(!document.getElementById('auxilios-operator-billing-css')){const l=document.createElement('link');l.id='auxilios-operator-billing-css';l.rel='stylesheet';l.href='/operator-billing.css';document.head.appendChild(l)}}
function ensureShell(){
  injectAssets();
  let screen=document.getElementById('screen-facturacion');
  if(!screen){const content=document.querySelector('.content');if(!content)return null;screen=document.createElement('div');screen.id='screen-facturacion';screen.className='screen ob-screen';content.appendChild(screen)}
  let nav=document.getElementById('nav-facturacion');
  if(!nav){const sidenav=document.querySelector('.sidenav'),bottom=sidenav?.querySelector('.nav-bottom');if(sidenav&&bottom){nav=document.createElement('div');nav.id='nav-facturacion';nav.className='nav-item';nav.innerHTML='<span class="nav-icon">$</span><span class="nav-label">Facturación</span>';nav.addEventListener('click',open);sidenav.insertBefore(nav,bottom)}}
  if(nav)nav.style.display=canRead()?'':'none';
  if(!screen.dataset.boundOb){screen.dataset.boundOb='1';screen.addEventListener('click',onClick);screen.addEventListener('input',onInput);}
  return screen;
}
function setTopbar(){const title=document.getElementById('topbar-title'),sub=document.getElementById('topbar-sub');if(title)title.textContent='FACTURACIÓN';if(sub)sub.textContent='Servicios finalizados · revisión de importes y tarifas vigentes'}
function open(){if(!canRead())return notify('Sin permiso para Facturación','error');const screen=ensureShell();if(!screen)return;window.dispatchEvent(new CustomEvent('auxilios:navigation-changed',{detail:{screen:'facturacion'}}));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));screen.classList.add('active');document.getElementById('nav-facturacion')?.classList.add('active');setTopbar();render();load();}

function kpis(){const changed=S.rows.filter(r=>r.pricing_error==null&&Math.abs(num(r.billing_delta))>.009),errors=S.rows.filter(r=>r.pricing_error),net=changed.reduce((a,r)=>a+num(r.billing_delta),0);return[
  ['Pendientes',S.kpis.pending_count||0,money(S.kpis.pending_amount||0),'A revisar'],
  ['Revisados',S.kpis.reviewed_count||0,money(S.kpis.reviewed_amount||0),'Listos para futura facturación'],
  ['Cambios tarifarios',changed.length,money(net),'Diferencia vs. cierre operativo'],
  ['Errores de tarifa',errors.length,errors.length?'Requieren configuración':'Sin errores','Motor contractual vigente']
]}
function render(){const screen=ensureShell();if(!screen)return;const cards=kpis();screen.innerHTML=`<div class="ob-shell">
  <div class="ob-head"><div><h2>Facturación</h2><p>El importe se calcula con la tarifa vigente para la fecha real del servicio. El snapshot operativo queda sólo como auditoría.</p></div><div class="ob-head-actions"><button class="ob-button" type="button" data-ob="refresh">↻ Actualizar</button></div></div>
  <div class="ob-kpis">${cards.map(([l,n,v,s])=>`<article class="ob-kpi"><small>${esc(l)}</small><b>${esc(n)}</b><span>${esc(v)} · ${esc(s)}</span></article>`).join('')}</div>
  <div class="ob-toolbar"><div class="ob-tabs"><button class="ob-tab ${S.tab==='pending'?'active':''}" type="button" data-ob-tab="pending">Pendientes</button><button class="ob-tab ${S.tab==='reviewed'?'active':''}" type="button" data-ob-tab="reviewed">Revisados</button></div><input class="ob-search" id="ob-search" placeholder="Buscar prestadora, código, patente…" value="${esc(S.search)}"></div>
  <div class="ob-table-card">${S.loading?'<div class="ob-empty">Calculando importes con tarifas vigentes…</div>':tableMarkup()}</div>
  <div id="ob-detail-backdrop" class="ob-detail-backdrop" ${S.detail||S.detailLoading?'':'hidden'}>${S.detailLoading?'<aside class="ob-detail"><div class="ob-empty">Calculando detalle de facturación…</div></aside>':S.detail?detailMarkup():''}</div>
</div>`;}
function tableMarkup(){const rows=S.rows.filter(r=>r.billing_status===S.tab);if(!rows.length)return`<div class="ob-empty">${S.tab==='pending'?'No hay servicios pendientes de revisión.':'Todavía no hay servicios revisados.'}</div>`;return`<div class="ob-table-wrap"><table class="ob-table"><thead><tr><th>Prestadora</th><th>Fecha</th><th>Servicio</th><th>Código</th><th>Patente</th><th>Tarifa</th><th>Importe cierre</th><th>Importe actual</th><th>Diferencia</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(rowMarkup).join('')}</tbody></table></div>`}
function deltaMarkup(v){if(v==null)return'<span class="ob-delta same">—</span>';const n=num(v),cls=Math.abs(n)<.009?'same':n>0?'up':'down',sign=n>0?'+':'';return`<span class="ob-delta ${cls}">${sign}${esc(money(n))}</span>`}
function rowMarkup(r){const stale=r.billing_status==='reviewed'&&r.last_reviewed_amount!=null&&Math.abs(num(r.current_company_amount)-num(r.last_reviewed_amount))>.009;return`<tr data-billing-service="${esc(r.service_id)}"><td class="ob-company"><b>${esc(r.company_name)}</b><small>${esc(r.billing_base_name||'')}</small></td><td>${esc(date(r.completed_at||r.scheduled_for))}</td><td><b>${esc(r.service_name)}</b><div class="ob-code">${esc(r.service_number)}</div></td><td class="ob-code">${esc(r.service_order_number||'—')}</td><td class="ob-code">${esc(r.vehicle_plate||'—')}</td><td>${r.pricing_error?`<div class="ob-error">${esc(r.pricing_error)}</div>`:`${esc(r.rate_card_name||'—')}<div class="ob-code">v${esc(r.rate_card_version||'—')}</div>`}</td><td class="ob-money">${esc(money(r.stored_company_amount,r.currency))}</td><td class="ob-money">${esc(money(r.current_company_amount,r.currency))}</td><td>${deltaMarkup(r.billing_delta)}</td><td><span class="ob-status ${esc(r.billing_status)}">${stale?'Tarifa actualizada':r.billing_status==='pending'?'Pendiente':'Revisado'}</span></td><td><button class="ob-button" type="button" data-ob-detail="${esc(r.service_id)}">Ver</button></td></tr>`}

function componentMarkup(q){const rows=[...(Array.isArray(q.components)?q.components:[])];if(num(q.surcharge_total)>0)rows.push({service_name:'Recargo',quantity:1,unit_price:q.surcharge_total,subtotal:q.surcharge_total,pricing_unit:'recargo'});if(num(q.toll_total)>0)rows.push({service_name:'Peajes facturables',quantity:1,unit_price:q.toll_total,subtotal:q.toll_total,pricing_unit:'peajes'});if(!rows.length)return'<div class="ob-empty">Sin componentes.</div>';return`<div class="ob-components">${rows.map(x=>`<div class="ob-component"><div><b>${esc(x.service_name||x.role||'Concepto')}</b><small>${esc(x.pricing_unit||'')} · ${esc(x.quantity??1)} × ${esc(money(x.unit_price||0,q.currency))}</small></div><small>${esc(x.price_source||'')}</small><b class="ob-money">${esc(money(x.subtotal||0,q.currency))}</b></div>`).join('')}</div>`}
function revisionsMarkup(rows,currency){if(!rows?.length)return'<div class="ob-empty">Todavía no hay revisiones registradas.</div>';return`<div class="ob-history">${rows.map(r=>`<article><b>${esc((r.billing_status||'').toUpperCase())} · ${esc(money(r.company_amount,r.currency||currency))}</b><small>${esc(r.created_by_name||'Usuario')} · ${esc(date(r.created_at))}${r.reason?` · ${esc(r.reason)}`:''}</small></article>`).join('')}</div>`}
function detailMarkup(){const d=S.detail,s=d.service||{},q=d.current_quote||{},delta=num(q.billing_delta),reviewedAmount=(d.revisions||[]).find(r=>r.billing_status==='reviewed')?.company_amount,reviewStale=s.billing_status==='reviewed'&&reviewedAmount!=null&&Math.abs(num(reviewedAmount)-num(q.current_company_amount))>.009;return`<aside class="ob-detail">
  <div class="ob-detail-head"><div><small>Facturación · ${esc(s.billing_status==='pending'?'Pendiente':'Revisado')}</small><h3>${esc(s.service_number||'Servicio')}</h3></div><button class="ob-button" type="button" data-ob="close-detail">× Cerrar</button></div>
  <div class="ob-detail-body">
    <div class="ob-summary"><article><small>Importe actual</small><b>${esc(money(q.current_company_amount,q.currency))}</b></article><article><small>Importe al cierre</small><b>${esc(money(q.stored_company_amount,q.currency))}</b></article><article><small>Diferencia</small><b>${delta>0?'+':''}${esc(money(delta,q.currency))}</b></article></div>
    ${Math.abs(delta)>.009?`<section class="ob-section"><h4>Cambio tarifario detectado</h4><div class="ob-field"><b>La tarifa vigente para la fecha del servicio produce una diferencia de ${delta>0?'+':''}${esc(money(delta,q.currency))} respecto del cierre operativo.</b><small>Facturación usa el importe actual. El cierre original no se sobrescribe.</small></div></section>`:''}
    ${reviewStale?`<section class="ob-section"><h4>Revisión desactualizada</h4><div class="ob-field"><b>La tarifa cambió después de la última revisión.</b><small>Este caso se automatizará con la propagación retroactiva antes de habilitar Facturado.</small></div></section>`:''}
    <section class="ob-section"><h4>Servicio</h4><div class="ob-grid"><div class="ob-field"><small>Prestadora</small><b>${esc(s.company_name||'—')}</b></div><div class="ob-field"><small>Código prestadora</small><b>${esc(s.service_order_number||'—')}</b></div><div class="ob-field"><small>Tipo</small><b>${esc(s.service_name||'—')}</b></div><div class="ob-field"><small>Patente</small><b>${esc(s.vehicle_plate||'—')}</b></div><div class="ob-field"><small>Fecha servicio</small><b>${esc(date(s.scheduled_for))}</b></div><div class="ob-field"><small>Finalizado</small><b>${esc(date(s.completed_at))}</b></div><div class="ob-field"><small>Origen</small><b>${esc(s.origin||'—')}</b></div><div class="ob-field"><small>Destino</small><b>${esc(s.destination||'—')}</b></div></div></section>
    <section class="ob-section"><h4>Tarifa aplicada ahora</h4><div class="ob-grid"><div class="ob-field"><small>Tarifario</small><b>${esc(q.rate_card_name||'—')} · v${esc(q.rate_card_version||'—')}</b></div><div class="ob-field"><small>Contrato</small><b>${esc(q.contract_name||'—')}</b></div><div class="ob-field"><small>Radio cubierto</small><b>${q.covered_radius_km==null?'—':esc(`${q.covered_radius_km} km`)}</b></div><div class="ob-field"><small>KM facturables</small><b>${esc(`${q.billable_distance_km??0} km`)}</b></div></div></section>
    <section class="ob-section"><h4>Composición</h4>${componentMarkup(q)}</section>
    ${s.billing_status==='pending'&&canReview()?reviewMarkup():''}
    <section class="ob-section"><h4>Historial de Facturación</h4>${revisionsMarkup(d.revisions,q.currency)}</section>
  </div></aside>`}
function reviewMarkup(){if(!S.confirmReview)return'<section class="ob-review-box"><div><b>Revisión administrativa</b><div class="ob-field"><small>Al marcar REVISADO se guarda una revisión con el tarifario y el importe actuales. Todavía no se genera ninguna factura.</small></div></div><div class="ob-review-actions"><button class="ob-button success" type="button" data-ob="prepare-review">Marcar REVISADO</button></div></section>';return`<section class="ob-review-box"><div><b>Confirmar revisión</b><div class="ob-field"><small>Esta confirmación pertenece a este detalle y se resuelve antes de salir de Facturación.</small></div></div><textarea id="ob-review-notes" maxlength="500" placeholder="Nota de revisión (opcional)"></textarea><div class="ob-review-actions"><button class="ob-button" type="button" data-ob="cancel-review">Cancelar</button><button class="ob-button success" type="button" data-ob="confirm-review">Confirmar REVISADO</button></div></section>`}

async function load(){if(S.loading||!db()||!canRead())return;S.loading=true;render();try{const {data,error}=await db().rpc('list_operator_billing_services_v1',{p_status:null,p_search:S.search||null});if(error)throw error;S.rows=Array.isArray(data?.rows)?data.rows:[];S.kpis=data?.kpis||{};}catch(e){notify(e.message||'No se pudo cargar Facturación','error');S.rows=[];S.kpis={};}finally{S.loading=false;render()}}
async function openDetail(id){if(!id||S.detailLoading)return;S.detail=null;S.detailLoading=true;S.confirmReview=false;render();try{const {data,error}=await db().rpc('get_operator_billing_service_detail_v1',{p_service_id:id});if(error)throw error;S.detail=data;}catch(e){notify(e.message||'No se pudo abrir el detalle','error');S.detail=null;}finally{S.detailLoading=false;render()}}
function closeDetail(){S.detail=null;S.detailLoading=false;S.confirmReview=false;render()}
async function review(){const id=S.detail?.service?.service_id;if(!id||!canReview())return;const notes=document.getElementById('ob-review-notes')?.value||'',button=document.querySelector('[data-ob="confirm-review"]');if(button){button.disabled=true;button.textContent='Confirmando…'}try{const {data,error}=await db().rpc('review_operator_billing_service_v1',{p_service_id:id,p_notes:notes||null});if(error)throw error;notify('Servicio marcado como REVISADO','success');S.detail=data;S.confirmReview=false;await load();S.tab='reviewed';await openDetail(id);}catch(e){notify(e.message||'No se pudo revisar el servicio','error');if(button?.isConnected){button.disabled=false;button.textContent='Confirmar REVISADO'}}}
function onInput(e){if(e.target.id!=='ob-search')return;S.search=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(load,280)}
function onClick(e){const tab=e.target.closest?.('[data-ob-tab]');if(tab){S.tab=tab.dataset.obTab;render();return}const detail=e.target.closest?.('[data-ob-detail]');if(detail){openDetail(detail.dataset.obDetail);return}const b=e.target.closest?.('[data-ob]');if(!b)return;const a=b.dataset.ob;if(a==='refresh')load();else if(a==='close-detail')closeDetail();else if(a==='prepare-review'){S.confirmReview=true;render()}else if(a==='cancel-review'){S.confirmReview=false;render()}else if(a==='confirm-review')review();}
function init(){if(!canRead())return;ensureShell();window.AuxiliosBilling={open,load,canRead,canReview};}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
