/* AuxiliOS · Facturación · mesa administrativa canónica */
(()=>{'use strict';
const B=window.OperatorBilling=window.OperatorBilling||{};
const S=B.S={rows:[],tollRows:[],tollTotal:0,filters:{companies:[],periods:[]},tab:'pending',search:'',company:'',period:'',selected:new Set(),selectionCompanyId:'',loading:false,detail:null,detailLoading:false,confirmReview:false,confirmBatch:false,actionConfirm:null,searchTimer:null};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const profile=()=>typeof PERFIL_USUARIO!=='undefined'?PERFIL_USUARIO:(window.PERFIL_USUARIO||{});
const role=()=>norm(profile()?.roles?.name||profile()?.role?.name||profile()?.role||profile()?.role_name||'');
const canRead=()=>['administracion','facturacion','supervision'].includes(role());
const canReview=()=>['administracion','facturacion'].includes(role());
const canCorrect=()=>role()==='administracion';
const canRevert=()=>['administracion','facturacion'].includes(role());
const db=()=>typeof _db!=='undefined'?_db:null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const notify=(m,t='info')=>typeof window.toast==='function'?window.toast(m,t):console[t==='error'?'error':'log'](m);
const money=(v,c='ARS')=>new Intl.NumberFormat('es-AR',{style:'currency',currency:c||'ARS',maximumFractionDigits:2}).format(num(v));
function dateParts(v){if(!v)return{day:'—',time:'—'};const d=new Date(v),p=new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d),g=t=>p.find(x=>x.type===t)?.value||'';return{day:`${g('day')}/${g('month')}/${g('year')}`,time:`${g('hour')}:${g('minute')}`};}
const date=v=>v?new Date(v).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function periodLabel(value){if(!value)return'Todos los períodos';const [y,m]=value.split('-').map(Number);if(!y||!m)return value;return new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,1))).replace(/^./,x=>x.toUpperCase());}
function periodBounds(value){if(!value)return{start:null,end:null};const [y,m]=value.split('-').map(Number);if(!y||!m)return{start:null,end:null};const pad=n=>String(n).padStart(2,'0'),last=new Date(Date.UTC(y,m,0)).getUTCDate();return{start:`${y}-${pad(m)}-01`,end:`${y}-${pad(m)}-${pad(last)}`};}
function injectAssets(){if(!document.getElementById('auxilios-operator-billing-css')){const l=document.createElement('link');l.id='auxilios-operator-billing-css';l.rel='stylesheet';l.href='/operator-billing.css';document.head.appendChild(l)}}
function ensureShell(){if(!document.getElementById('auxilios-operator-billing-css'))injectAssets();let screen=document.getElementById('screen-facturacion');if(!screen){const content=document.querySelector('.content');if(!content)return null;screen=document.createElement('div');screen.id='screen-facturacion';screen.className='screen ob-screen';content.appendChild(screen)}let nav=document.getElementById('nav-facturacion');if(!nav){const sidenav=document.querySelector('.sidenav'),bottom=sidenav?.querySelector('.nav-bottom');if(sidenav&&bottom){nav=document.createElement('div');nav.id='nav-facturacion';nav.className='nav-item';nav.innerHTML='<span class="nav-icon">$</span><span class="nav-label">Facturación</span>';nav.addEventListener('click',open);sidenav.insertBefore(nav,bottom)}}if(nav)nav.style.display=canRead()?'':'none';if(!screen.dataset.boundOb){screen.dataset.boundOb='1';screen.addEventListener('click',onClick);screen.addEventListener('input',onInput);screen.addEventListener('change',onChange);}return screen;}
function setTopbar(){const title=document.getElementById('topbar-title'),sub=document.getElementById('topbar-sub');if(title)title.textContent='FACTURACIÓN';if(sub)sub.textContent='Prestadora · período · gestión de servicios y peajes';}
function open(){if(!canRead())return notify('Sin permiso para Facturación','error');const screen=ensureShell();if(!screen)return;window.dispatchEvent(new CustomEvent('auxilios:navigation-changed',{detail:{screen:'facturacion'}}));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));screen.classList.add('active');document.getElementById('nav-facturacion')?.classList.add('active');setTopbar();render();load();}
function clearSelection(){S.selected.clear();S.selectionCompanyId='';S.confirmBatch=false;}
function companyName(id){return S.filters.companies.find(x=>String(x.company_id)===String(id))?.company_name||S.rows.find(x=>String(x.company_id)===String(id))?.company_name||S.tollRows.find(x=>String(x.company_id)===String(id))?.company_name||'Prestadora';}
function selectedRows(){return S.rows.filter(r=>S.selected.has(String(r.service_id)));}
function visibleRows(){return S.rows.filter(r=>r.billing_status===S.tab);}
function filterOptions(){const companies=['<option value="">Todas las prestadoras</option>',...S.filters.companies.map(x=>`<option value="${esc(x.company_id)}" ${String(S.company)===String(x.company_id)?'selected':''}>${esc(x.company_name)}</option>`)].join('');const periods=['<option value="">Todos los períodos</option>',...S.filters.periods.map(p=>`<option value="${esc(p)}" ${S.period===p?'selected':''}>${esc(periodLabel(p))}</option>`)].join('');return{companies,periods};}
function excelMenuMarkup(){const count=S.tab==='tolls'?S.tollRows.length:S.rows.filter(r=>r.billing_status===S.tab).length,selected=S.selected.size,tab=S.tab==='reviewed'?'Revisados':S.tab==='tolls'?'Peajes':'Pendientes';return`<div class="obx-menu" role="menu"><button type="button" data-ob="excel-current"><b>Vista actual</b><small>${esc(tab)} · ${count} registros</small></button><button type="button" data-ob="excel-selected" ${S.tab==='tolls'||!selected?'disabled':''}><b>Selección</b><small>${selected?`${selected} servicios seleccionados`:'Seleccioná servicios primero'}</small></button><button type="button" data-ob="excel-all"><b>Todo lo filtrado</b><small>Pendientes + Revisados + Peajes</small></button></div>`;}
function closeRowActionMenu(){document.querySelectorAll('[data-ob-row-menu][aria-expanded="true"]').forEach(x=>x.setAttribute('aria-expanded','false'));document.getElementById('ob-row-action-menu')?.remove();}
function rowActionMenuMarkup(id){return`<button type="button" data-ob-row-action="view" data-service-id="${esc(id)}">Visualizar</button>${canCorrect()?`<button type="button" data-ob-row-action="edit" data-service-id="${esc(id)}" title="Modificar servicio">Modificar</button>`:''}${canRevert()?`<button type="button" data-ob-row-action="revert" data-service-id="${esc(id)}">Revertir</button>`:''}${canCorrect()?`<button type="button" class="danger" data-ob-row-action="annul" data-service-id="${esc(id)}">Anular</button>`:''}`;}
function toggleRowActionMenu(trigger,id){const existing=document.getElementById('ob-row-action-menu');if(existing?.dataset.serviceId===String(id)){closeRowActionMenu();return;}closeRowActionMenu();const menu=document.createElement('div');menu.id='ob-row-action-menu';menu.className='ob-row-action-menu';menu.dataset.serviceId=String(id);menu.setAttribute('role','menu');menu.innerHTML=rowActionMenuMarkup(id);document.body.appendChild(menu);const r=trigger.getBoundingClientRect(),margin=8,gap=6;let left=Math.max(margin,Math.min(r.right-menu.offsetWidth,window.innerWidth-menu.offsetWidth-margin)),top=r.bottom+gap;if(top+menu.offsetHeight>window.innerHeight-margin)top=Math.max(margin,r.top-menu.offsetHeight-gap);menu.style.left=`${left}px`;menu.style.top=`${top}px`;trigger.setAttribute('aria-expanded','true');}
function render(){const screen=ensureShell();if(!screen)return;closeRowActionMenu();document.querySelector('.topbar-right #obx-wrap')?.remove();const opts=filterOptions(),isTolls=S.tab==='tolls',excelControl=S.selected.size?'<div id="obx-wrap" class="obx-wrap"><button type="button" class="obx-trigger" id="obx-trigger" aria-haspopup="menu" aria-expanded="false" data-ob="excel-toggle">⇩ Excel</button></div>':'';screen.innerHTML=`<div class="ob-shell">
  <div class="ob-toolbar"><div class="ob-tabs"><button class="ob-tab ${S.tab==='pending'?'active':''}" type="button" data-ob-tab="pending">Pendientes</button><button class="ob-tab ${S.tab==='reviewed'?'active':''}" type="button" data-ob-tab="reviewed">Revisados</button><button class="ob-tab ${S.tab==='tolls'?'active':''}" type="button" data-ob-tab="tolls">Peajes</button></div><div class="ob-filters"><input class="ob-search" id="ob-search" placeholder="Buscar código, cliente, origen, destino…" value="${esc(S.search)}"><select class="ob-filter" id="ob-company-filter">${opts.companies}</select><select class="ob-filter" id="ob-period-filter">${opts.periods}</select>${excelControl}<button class="ob-button ob-filter-action" type="button" data-ob="refresh">↻ Actualizar</button></div></div>
  ${isTolls?'':selectionMarkup()}
  <div class="ob-table-card">${S.loading?'<div class="ob-empty">Calculando servicios y peajes del período…</div>':tableMarkup()}</div>
  <div id="ob-detail-backdrop" class="ob-detail-backdrop" ${S.detail||S.detailLoading?'':'hidden'}>${S.detailLoading?'<aside class="ob-detail"><div class="ob-empty">Calculando detalle de facturación…</div></aside>':S.detail?detailMarkup():''}</div>
</div>`;}
function selectionMarkup(){const rows=selectedRows();if(!rows.length)return'';const total=rows.reduce((a,r)=>a+num(r.current_company_amount),0),currency=rows[0]?.currency||'ARS';if(S.confirmBatch)return`<section class="ob-selection ob-selection-confirm"><div><b>Confirmar revisión masiva</b><small>${rows.length} servicios · ${esc(companyName(S.selectionCompanyId))} · ${esc(money(total,currency))}</small></div><input id="ob-bulk-note" maxlength="500" placeholder="Nota de revisión (opcional)"><div><button class="ob-button" data-ob="cancel-batch">Cancelar</button><button class="ob-button success" data-ob="confirm-batch">Confirmar ${rows.length}</button></div></section>`;return`<section class="ob-selection"><div><b>${rows.length} seleccionados</b><small>${esc(companyName(S.selectionCompanyId))} · ${esc(money(total,currency))}</small></div><div class="ob-selection-actions"><button class="ob-button" data-ob="clear-selection">Limpiar</button>${S.tab==='pending'&&canReview()?'<button class="ob-button success" data-ob="prepare-batch">Marcar REVISADOS</button>':'<button class="ob-button primary" disabled title="Se habilitará con la entidad Factura">Facturar selección · siguiente etapa</button>'}</div></section>`;}
function tableMarkup(){if(S.tab==='tolls')return tollTableMarkup();const rows=visibleRows();if(!rows.length)return`<div class="ob-empty">${S.tab==='pending'?'No hay servicios pendientes con estos filtros.':'No hay servicios revisados con estos filtros.'}</div>`;const selectable=rows.filter(r=>!r.pricing_error),companies=new Set(selectable.map(r=>String(r.company_id))),allSelected=selectable.length>0&&selectable.every(r=>S.selected.has(String(r.service_id))),headerDisabled=companies.size>1&&S.selected.size===0;return`<div class="ob-table-wrap"><table class="ob-table"><thead><tr><th class="ob-check"><input type="checkbox" data-ob-select-all ${allSelected?'checked':''} ${headerDisabled?'disabled title="Filtrá una prestadora para seleccionar todo"':''}></th><th>Fecha/Hora</th><th>Prestadora</th><th>Base</th><th>Tipo de Servicio</th><th>Origen</th><th>Destino</th><th>Cliente</th><th>KM</th><th class="ob-actions"></th></tr></thead><tbody>${rows.map(rowMarkup).join('')}</tbody></table></div>`;}
function rowMarkup(r){const id=String(r.service_id),dp=dateParts(r.scheduled_for),checked=S.selected.has(id),disabled=!!r.pricing_error;return`<tr data-billing-service="${esc(id)}" class="${checked?'selected':''}"><td class="ob-check"><input type="checkbox" data-ob-select="${esc(id)}" ${checked?'checked':''} ${disabled?'disabled title="Corregí el error tarifario antes de seleccionar"':''}></td><td><b>${esc(dp.day)}</b><small>${esc(dp.time)}</small></td><td><b>${esc(r.company_name||'—')}</b></td><td><b>${esc(r.billing_base_name||'—')}</b></td><td><b>${esc(r.service_name||'—')}</b>${r.pricing_error?`<small class="ob-error">${esc(r.pricing_error)}</small>`:''}</td><td class="ob-place">${esc(r.origin||'—')}</td><td class="ob-place">${esc(r.destination||'—')}</td><td><b>${esc(r.customer_name||'—')}</b></td><td class="ob-km">${esc(num(r.km).toLocaleString('es-AR',{maximumFractionDigits:1}))} km</td><td class="ob-actions"><button class="ob-row-menu-trigger" type="button" data-ob-row-menu="${esc(id)}" aria-haspopup="menu" aria-expanded="false" title="Acciones del servicio" aria-label="Acciones del servicio">⋯</button></td></tr>`;}
function tollTableMarkup(){const rows=S.tollRows;if(!rows.length)return'<div class="ob-empty">No hay peajes con facturación separada para estos filtros.</div>';return`<div class="ob-table-wrap"><table class="ob-table"><thead><tr><th>Fecha/Hora</th><th>Prestadora</th><th>Servicio</th><th>Peaje</th><th>Ruta</th><th>Base</th><th>Importe</th><th>Servicio</th></tr></thead><tbody>${rows.map(tollRowMarkup).join('')}</tbody></table></div>`;}
function tollRowMarkup(r){const dp=dateParts(r.scheduled_for),route=[r.road,r.direction].filter(Boolean).join(' · ')||`${r.origin||'—'} → ${r.destination||'—'}`,status=r.service_billing_status==='reviewed'?'REVISADO':'PENDIENTE';return`<tr><td><b>${esc(dp.day)}</b><small>${esc(dp.time)}</small></td><td><b>${esc(r.company_name||'—')}</b></td><td><b>${esc(r.service_order_number||r.service_number||'—')}</b><small>${esc(r.vehicle_plate||'')}</small></td><td><b>${esc(r.toll_name||'Peaje')}</b><small>${esc(r.source||'')}</small></td><td class="ob-place">${esc(route)}</td><td><b>${esc(r.billing_base_name||'—')}</b></td><td><b class="ob-money">${esc(money(r.amount,r.currency))}</b></td><td><b>${esc(status)}</b><small>Peaje separado del total</small></td></tr>`;}
function componentMarkup(q){const rows=[...(Array.isArray(q.components)?q.components:[])];if(num(q.surcharge_total)>0)rows.push({service_name:'Recargo',quantity:1,unit_price:q.surcharge_total,subtotal:q.surcharge_total,pricing_unit:'recargo'});if(q.toll_billing_mode!=='separate'&&num(q.toll_total)>0)rows.push({service_name:'Peajes facturables',quantity:1,unit_price:q.toll_total,subtotal:q.toll_total,pricing_unit:'peajes'});if(!rows.length)return'<div class="ob-empty">Sin componentes.</div>';return`<div class="ob-components">${rows.map(x=>`<div class="ob-component"><div><b>${esc(x.service_name||x.role||'Concepto')}</b><small>${esc(x.pricing_unit||'')} · ${esc(x.quantity??1)} × ${esc(money(x.unit_price||0,q.currency))}</small></div><small>${esc(x.price_source||'')}</small><b class="ob-money">${esc(money(x.subtotal||0,q.currency))}</b></div>`).join('')}</div>`;}
function revisionsMarkup(rows,currency){if(!rows?.length)return'<div class="ob-empty">Todavía no hay movimientos de Facturación.</div>';return`<div class="ob-history">${rows.map(r=>`<article><b>${esc((r.billing_status||'').toUpperCase())} · ${esc(money(r.company_amount,r.currency||currency))}</b><small>${esc(r.created_by_name||'Usuario')} · ${esc(date(r.created_at))}${r.reason?` · ${esc(r.reason)}`:''}</small></article>`).join('')}</div>`;}
function actionConfirmMarkup(){if(!S.actionConfirm)return'';const type=S.actionConfirm,title=type==='annul'?'Anular servicio FINALIZADO':'Revertir Facturación',copy=type==='annul'?'El servicio pasará a ANULADO, saldrá de Facturación y quedará en Servicios → Historial. La acción queda auditada automáticamente.':'El servicio saldrá de Facturación y conservará FINALIZADO en Servicios → Historial. La acción queda auditada automáticamente.';return`<section class="ob-action-confirm ${type==='annul'?'danger':''}"><div><b>${title}</b><small>${copy}</small></div><div class="ob-review-actions"><button class="ob-button" data-ob="cancel-action">Cancelar</button><button class="ob-button ${type==='annul'?'danger':'primary'}" data-ob="confirm-action">Confirmar</button></div></section>`;}
function detailMarkup(){const d=S.detail,s=d.service||{},q=d.current_quote||{},delta=num(q.billing_delta),reviewedAmount=(d.revisions||[]).find(r=>r.billing_status==='reviewed')?.company_amount,reviewStale=s.billing_status==='reviewed'&&reviewedAmount!=null&&Math.abs(num(reviewedAmount)-num(q.current_company_amount))>.009,separateTolls=q.toll_billing_mode==='separate'&&num(q.separate_toll_amount)>0;return`<aside class="ob-detail">
  <div class="ob-detail-head"><div><small>Facturación · ${esc(s.billing_status==='pending'?'Pendiente':'Revisado')}</small><h3>${esc(s.service_number||'Servicio')}</h3></div><button class="ob-button" type="button" data-ob="close-detail">× Cerrar</button></div>
  <div class="ob-detail-body">
    <div class="ob-summary"><article><small>Importe actual</small><b>${esc(money(q.current_company_amount,q.currency))}</b></article><article><small>Importe al cierre</small><b>${esc(money(q.stored_company_amount,q.currency))}</b></article><article><small>Diferencia</small><b>${delta>0?'+':''}${esc(money(delta,q.currency))}</b></article></div>
    ${separateTolls?`<section class="ob-section"><h4>Peajes facturados por separado</h4><div class="ob-field"><b>${esc(money(q.separate_toll_amount,q.currency))}</b><small>Este importe no forma parte del total del servicio. Se administra desde Facturación → Peajes.</small></div></section>`:''}
    ${Math.abs(delta)>.009?`<section class="ob-section"><h4>Cambio tarifario detectado</h4><div class="ob-field"><b>${delta>0?'+':''}${esc(money(delta,q.currency))} respecto del cierre operativo.</b><small>Se usa la tarifa vigente para la fecha del servicio; el snapshot original queda como auditoría.</small></div></section>`:''}
    ${reviewStale?'<section class="ob-section"><h4>Revisión desactualizada</h4><div class="ob-field"><b>La tarifa cambió después de la última revisión.</b><small>Debe volver a revisarse antes de facturar.</small></div></section>':''}
    <section class="ob-section"><h4>Servicio</h4><div class="ob-grid"><div class="ob-field"><small>Fecha/Hora</small><b>${esc(date(s.scheduled_for))}</b></div><div class="ob-field"><small>Prestadora</small><b>${esc(s.company_name||'—')}</b></div><div class="ob-field"><small>Base</small><b>${esc(s.billing_base_name||'—')}</b></div><div class="ob-field"><small>Tipo</small><b>${esc(s.service_name||'—')}</b></div><div class="ob-field"><small>Origen</small><b>${esc(s.origin||'—')}</b></div><div class="ob-field"><small>Destino</small><b>${esc(s.destination||'—')}</b></div><div class="ob-field"><small>Cliente</small><b>${esc(s.customer_name||'—')}</b></div><div class="ob-field"><small>Patente</small><b>${esc(s.vehicle_plate||'—')}</b></div></div></section>
    <section class="ob-section"><h4>Tarifa aplicada ahora</h4><div class="ob-grid"><div class="ob-field"><small>Tarifario</small><b>${esc(q.rate_card_name||'—')} · v${esc(q.rate_card_version||'—')}</b></div><div class="ob-field"><small>Contrato</small><b>${esc(q.contract_name||'—')}</b></div><div class="ob-field"><small>Radio cubierto</small><b>${q.covered_radius_km==null?'—':esc(`${q.covered_radius_km} km`)}</b></div><div class="ob-field"><small>KM facturables</small><b>${esc(`${q.billable_distance_km??0} km`)}</b></div></div></section>
    <section class="ob-section"><h4>Composición</h4>${componentMarkup(q)}</section>
    ${actionConfirmMarkup()}
    ${s.billing_status==='pending'&&canReview()?reviewMarkup():''}
    <section class="ob-section"><h4>Historial de Facturación</h4>${revisionsMarkup(d.revisions,q.currency)}</section>
  </div></aside>`;}
function reviewMarkup(){if(!S.confirmReview)return'<section class="ob-review-box"><div><b>Revisión administrativa</b><div class="ob-field"><small>REVISADO deja el servicio preparado para la futura factura de esta Prestadora.</small></div></div><div class="ob-review-actions"><button class="ob-button success" type="button" data-ob="prepare-review">Marcar REVISADO</button></div></section>';return`<section class="ob-review-box"><div><b>Confirmar revisión</b><div class="ob-field"><small>Se guarda importe, tarifario, usuario y fecha de esta revisión.</small></div></div><textarea id="ob-review-notes" maxlength="500" placeholder="Nota de revisión (opcional)"></textarea><div class="ob-review-actions"><button class="ob-button" type="button" data-ob="cancel-review">Cancelar</button><button class="ob-button success" type="button" data-ob="confirm-review">Confirmar REVISADO</button></div></section>`;}
async function load(){if(S.loading||!db()||!canRead())return;S.loading=true;render();const bounds=periodBounds(S.period);try{const [services,tolls]=await Promise.all([db().rpc('list_operator_billing_services_v2',{p_status:null,p_search:S.search||null,p_company_id:S.company||null,p_period_start:bounds.start,p_period_end:bounds.end}),db().rpc('list_operator_billing_tolls_v1',{p_search:S.search||null,p_company_id:S.company||null,p_period_start:bounds.start,p_period_end:bounds.end})]);if(services.error)throw services.error;if(tolls.error)throw tolls.error;const data=services.data;S.rows=Array.isArray(data?.rows)?data.rows:[];S.filters={companies:Array.isArray(data?.filters?.companies)?data.filters.companies:[],periods:Array.isArray(data?.filters?.periods)?data.filters.periods:[]};S.tollRows=Array.isArray(tolls.data?.rows)?tolls.data.rows:[];S.tollTotal=num(tolls.data?.total_amount);for(const id of [...S.selected])if(!S.rows.some(r=>String(r.service_id)===id))S.selected.delete(id);if(!S.selected.size)S.selectionCompanyId='';}catch(e){notify(e.message||'No se pudo cargar Facturación','error');S.rows=[];S.tollRows=[];S.tollTotal=0;}finally{S.loading=false;render();}}
async function openDetail(id){if(!id||S.detailLoading)return;S.detail=null;S.detailLoading=true;S.confirmReview=false;S.actionConfirm=null;render();try{const {data,error}=await db().rpc('get_operator_billing_service_detail_v2',{p_service_id:id});if(error)throw error;S.detail=data;}catch(e){notify(e.message||'No se pudo abrir el detalle','error');S.detail=null;}finally{S.detailLoading=false;render();}}
async function openDetailAction(id,type){if(type==='annul'&&!canCorrect())return notify('Sin permiso para anular','error');if(type==='revert'&&!canRevert())return notify('Sin permiso para revertir Facturación','error');await openDetail(id);if(String(S.detail?.service?.service_id||'')!==String(id))return;S.actionConfirm=type;S.confirmReview=false;render();}
function closeDetail(){S.detail=null;S.detailLoading=false;S.confirmReview=false;S.actionConfirm=null;render();}
async function review(){const id=S.detail?.service?.service_id;if(!id||!canReview())return;const notes=document.getElementById('ob-review-notes')?.value||'',button=document.querySelector('[data-ob="confirm-review"]');if(button){button.disabled=true;button.textContent='Confirmando…'}try{const {data,error}=await db().rpc('review_operator_billing_service_v2',{p_service_id:id,p_notes:notes||null});if(error)throw error;S.detail=data;S.confirmReview=false;clearSelection();notify('Servicio REVISADO','success');await load();await openDetail(id);}catch(e){notify(e.message||'No se pudo revisar el servicio','error');render();}}
function toggleSelection(id,on){const row=S.rows.find(r=>String(r.service_id)===String(id));if(!row||row.pricing_error)return;if(on){if(S.selectionCompanyId&&String(S.selectionCompanyId)!==String(row.company_id)){notify('No se pueden seleccionar juntas diferentes prestadoras','warning');return render();}S.selectionCompanyId=String(row.company_id);S.selected.add(String(id));}else{S.selected.delete(String(id));if(!S.selected.size)S.selectionCompanyId='';}S.confirmBatch=false;render();}
function toggleAll(on){const rows=visibleRows().filter(r=>!r.pricing_error);if(!rows.length)return;const companies=new Set(rows.map(r=>String(r.company_id)));if(!S.selectionCompanyId&&companies.size>1)return notify('Filtrá una prestadora antes de seleccionar todos','warning');const companyId=S.selectionCompanyId||String(rows[0].company_id),eligible=rows.filter(r=>String(r.company_id)===companyId);if(on){S.selectionCompanyId=companyId;eligible.forEach(r=>S.selected.add(String(r.service_id)));}else eligible.forEach(r=>S.selected.delete(String(r.service_id)));if(!S.selected.size)S.selectionCompanyId='';S.confirmBatch=false;render();}
async function bulkReview(){const ids=[...S.selected];if(!ids.length||!canReview())return;const note=document.getElementById('ob-bulk-note')?.value||'',button=document.querySelector('[data-ob="confirm-batch"]');if(button){button.disabled=true;button.textContent='Confirmando…'}try{const {data,error}=await db().rpc('review_operator_billing_services_bulk_v2',{p_service_ids:ids,p_notes:note||null});if(error)throw error;notify(`${data?.reviewed_count||ids.length} servicios REVISADOS`,'success');clearSelection();await load();}catch(e){notify(e.message||'No se pudo revisar la selección','error');render();}}
async function confirmAdminAction(){const id=S.detail?.service?.service_id,type=S.actionConfirm;if(!id||!type)return;const button=document.querySelector('[data-ob="confirm-action"]');if(button){button.disabled=true;button.textContent='Procesando…'}try{const rpc=type==='annul'?'annul_operator_billing_service_v2':'revert_operator_billing_service_v2',{error}=await db().rpc(rpc,{p_service_id:id,p_reason:null});if(error)throw error;notify(type==='annul'?'Servicio ANULADO':'Facturación revertida','success');S.detail=null;S.actionConfirm=null;clearSelection();await load();if(typeof window.goTo==='function'){window.goTo('operaciones');window.cambiarVistaServicios?.('history');}}catch(e){notify(e.message||'No se pudo completar la acción','error');render();}}
function editServiceById(id){if(!id||!canCorrect())return;if(typeof window.editarServicioOperador!=='function')return notify('El editor de Servicios todavía se está cargando','warning');window.editarServicioOperador(id);}
function editService(){return editServiceById(S.detail?.service?.service_id);}
function handleRowAction(action,id){if(action==='view')return openDetail(id);if(action==='edit')return editServiceById(id);if(action==='revert')return openDetailAction(id,'revert');if(action==='annul')return openDetailAction(id,'annul');}
function onInput(e){if(e.target.id!=='ob-search')return;S.search=e.target.value;clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>{clearSelection();load();},300);}
function onChange(e){if(e.target.id==='ob-company-filter'){S.company=e.target.value||'';clearSelection();return load();}if(e.target.id==='ob-period-filter'){S.period=e.target.value||'';clearSelection();return load();}if(e.target.matches('[data-ob-select]'))return toggleSelection(e.target.dataset.obSelect,e.target.checked);if(e.target.matches('[data-ob-select-all]'))return toggleAll(e.target.checked);}
function onClick(e){const rowMenu=e.target.closest('[data-ob-row-menu]');if(rowMenu){e.stopPropagation();return toggleRowActionMenu(rowMenu,rowMenu.dataset.obRowMenu);}const excelAction=e.target.closest('[data-ob^="excel-"]')?.dataset.ob;if(excelAction){const wrap=document.getElementById('obx-wrap'),trigger=document.getElementById('obx-trigger'),menu=wrap?.querySelector('.obx-menu');if(excelAction==='excel-toggle'){if(menu){menu.remove();trigger?.setAttribute('aria-expanded','false');}else{wrap?.insertAdjacentHTML('beforeend',excelMenuMarkup());trigger?.setAttribute('aria-expanded','true');}return;}menu?.remove();trigger?.setAttribute('aria-expanded','false');if(excelAction==='excel-current')return window.OperatorBillingExcel?.exportCurrent?.();if(excelAction==='excel-selected')return window.OperatorBillingExcel?.exportSelected?.();if(excelAction==='excel-all')return window.OperatorBillingExcel?.exportAllFiltered?.();return;}const tab=e.target.closest('[data-ob-tab]');if(tab){S.tab=tab.dataset.obTab;clearSelection();return render();}const detail=e.target.closest('[data-ob-detail]');if(detail)return openDetail(detail.dataset.obDetail);const a=e.target.closest('[data-ob]')?.dataset.ob;if(!a)return;if(a==='refresh'){clearSelection();return load();}if(a==='close-detail')return closeDetail();if(a==='prepare-review'){S.confirmReview=true;return render();}if(a==='cancel-review'){S.confirmReview=false;return render();}if(a==='confirm-review')return review();if(a==='clear-selection'){clearSelection();return render();}if(a==='prepare-batch'){S.confirmBatch=true;return render();}if(a==='cancel-batch'){S.confirmBatch=false;return render();}if(a==='confirm-batch')return bulkReview();if(a==='edit-service')return editService();if(a==='prepare-revert'){S.actionConfirm='revert';S.confirmReview=false;return render();}if(a==='prepare-annul'){S.actionConfirm='annul';S.confirmReview=false;return render();}if(a==='cancel-action'){S.actionConfirm=null;return render();}if(a==='confirm-action')return confirmAdminAction();}
function onDocumentClick(e){const action=e.target.closest('[data-ob-row-action]');if(action){e.preventDefault();const type=action.dataset.obRowAction,id=action.dataset.serviceId;closeRowActionMenu();return handleRowAction(type,id);}if(!e.target.closest('[data-ob-row-menu]')&&!e.target.closest('#ob-row-action-menu'))closeRowActionMenu();}
function init(){ensureShell();document.addEventListener('click',onDocumentClick);document.addEventListener('scroll',closeRowActionMenu,true);window.addEventListener('resize',closeRowActionMenu);let attempts=0;const timer=setInterval(()=>{const nav=document.getElementById('nav-facturacion');if(nav)nav.style.display=canRead()?'':'none';if(canRead()&&db()){clearInterval(timer);}else if(++attempts>120)clearInterval(timer);},100);}
Object.assign(B,{open,load,render,openDetail,clearSelection,canRead,canReview,canCorrect});
Object.assign(window,{abrirFacturacionOperador:open,cargarFacturacionOperador:load});
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();