/* Salary matrix: explicit bases, recurring bonuses and concept commissions. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>{const raw=String(v??'').trim();const n=Number(raw.includes(',')?raw.replace(/\./g,'').replace(',','.'): /^\d{1,3}(\.\d{3})+$/.test(raw)?raw.replace(/\./g,''):raw);if(!Number.isFinite(n)||n<0)throw Error('Ingresá importes válidos y positivos.');return n;};
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
let catalog=[],openId=0;
function normalize(value){const x=value||{};if(!['real','billed'].includes(x.km_basis||'real'))throw Error('Base de kilómetros inválida.');const bonuses=(x.bonuses||[]).map(b=>({name:String(b.name||'').trim(),amount:money(b.amount)}));if(bonuses.some(b=>!b.name))throw Error('Nombrá cada bono mensual.');const seen=new Set();const commissions=(x.commissions||[]).map(c=>{if(!c.concept_id||!['extras','invoices'].includes(c.source)||!['fixed','percent'].includes(c.mode))throw Error('Completá concepto, origen y modalidad de la comisión.');const value=money(c.value);if(c.mode==='percent'&&value>100)throw Error('El porcentaje no puede superar 100.');const key=c.source+':'+c.concept_id;if(seen.has(key))throw Error('El concepto tiene dos reglas para el mismo origen.');seen.add(key);return{concept_id:c.concept_id,name:c.name||'',source:c.source,mode:c.mode,value};});return{km_basis:x.km_basis||'real',pay_km:x.pay_km!==false,pay_services:x.pay_services!==false,pay_presentismo:x.pay_presentismo!==false,bonuses,commissions};}
function calculate(matrix,sources,realKm){const m=normalize(matrix);const billedRows=[...new Map((sources.invoices||[]).filter(r=>r.km!=null).map(r=>[r.id??r,r])).values()];const km=m.km_basis==='billed'?round(billedRows.reduce((sum,r)=>sum+money(r.km),0)):money(realKm);const details=m.commissions.map(rule=>{const matching=(sources[rule.source]||[]).filter(r=>r.concept_id===rule.concept_id);const rows=[...new Map(matching.map(r=>[r.id??r,r])).values()];if(rule.mode==='percent'&&rows.some(r=>r.currency!=='ARS'))throw Error('La comisión porcentual requiere importes en ARS.');const base=rows.reduce((s,r)=>s+money(rule.mode==='fixed'?r.quantity:r.amount),0);return{...rule,base,total:round(base*rule.value/(rule.mode==='percent'?100:1)),records:rows.map(r=>r.id),record_details:rows.map(r=>({id:r.id,service_id:r.service_id,remito_id:r.remito_id,amount:r.amount,quantity:r.quantity,total:round(money(rule.mode==='fixed'?r.quantity:r.amount)*rule.value/(rule.mode==='percent'?100:1))}))};});return{km,bonus:round(m.bonuses.reduce((s,b)=>s+b.amount,0)),commission:round(details.reduce((s,c)=>s+c.total,0)),snapshot:{...m,commission_details:details,km_records:m.km_basis==='billed'?billedRows.map(r=>r.id):[],km}};}
function bonusRow(b={}){return `<div data-bonus class="pm-row"><input class="form-input" data-name placeholder="Nombre: desempeño, otro…" value="${esc(b.name||'')}"><input class="form-input" data-amount inputmode="decimal" placeholder="Importe mensual" value="${esc(b.amount??'')}"><button type="button" class="btn btn-ghost" onclick="this.parentElement.remove()" aria-label="Quitar bono">×</button></div>`;}
function commissionRow(c={}){return `<div data-commission class="pm-commission"><select class="form-input" data-concept><option value="">Concepto…</option>${catalog.map(x=>`<option value="${esc(x.concept_id)}" ${x.concept_id===c.concept_id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><select class="form-input" data-source><option value="extras">Adicional cobrado del remito</option><option value="invoices" ${c.source==='invoices'?'selected':''}>Servicio principal facturado</option></select><select class="form-input" data-mode><option value="fixed">$ por unidad</option><option value="percent" ${c.mode==='percent'?'selected':''}>% del importe</option></select><input class="form-input" data-value inputmode="decimal" placeholder="Valor" value="${esc(c.value??'')}"><button type="button" class="btn btn-ghost" onclick="this.parentElement.remove()">Quitar comisión</button></div>`;}
async function open(matrix){const requestId=++openId;let root=document.getElementById('payroll-matrix-fields');if(!root){root=document.createElement('section');root.id='payroll-matrix-fields';document.querySelector('#modal-esquema-edit .modal-body').appendChild(root);}root.innerHTML='<p>Cargando matriz…</p>';const {data,error}=await _db.rpc('list_service_types_config',{p_include_inactive:true});if(requestId!==openId)return;if(error){root.innerHTML='<p role="alert">No se pudo cargar el catálogo. Cerrá y reintentá.</p>';throw error;}catalog=data||[];const m=normalize(matrix);root.innerHTML=`<h3>Matriz de remuneración</h3><div class="pm-concepts"><label><input type="checkbox" id="pm-pay-services" ${m.pay_services?'checked':''}> <span><b>Pagar por servicio</b><small>Importe fijo por cada remito firmado.</small></span></label><label><input type="checkbox" id="pm-pay-km" ${m.pay_km?'checked':''}> <span><b>Pagar por kilómetros</b><small>Elegí qué distancia se liquida.</small></span></label><select class="form-input" id="pm-km"><option value="real">KM reales de jornada (odómetro final − inicial)</option><option value="billed" ${m.km_basis==='billed'?'selected':''}>KM facturados de los servicios</option></select><label><input type="checkbox" id="pm-pay-presentismo" ${m.pay_presentismo?'checked':''}> <span><b>Aplicar presentismo</b><small>Se paga si tuvo jornadas y no registró incidentes en el mes.</small></span></label></div><h4>Bonos mensuales</h4><div id="pm-bonuses">${m.bonuses.map(bonusRow).join('')}</div><button type="button" class="btn btn-ghost" onclick="PayrollMatrix.addBonus()">+ Bono</button><button type="button" class="btn btn-ghost" onclick="PayrollMatrix.addBonus({name:'Bono mensual',amount:280000})">+ Bono de $280.000</button><h4>Comisiones por concepto</h4><div id="pm-commissions">${m.commissions.map(commissionRow).join('')}</div><button type="button" class="btn btn-ghost" onclick="PayrollMatrix.addCommission()">+ Comisión</button><p class="pm-help">Las comisiones se calculan únicamente sobre conceptos cobrados y documentos válidos.</p>`;}
function read(){const root=document.getElementById('payroll-matrix-fields');if(!root?.querySelector('#pm-km'))throw Error('Esperá a que cargue la matriz.');return normalize({km_basis:root.querySelector('#pm-km').value,pay_km:root.querySelector('#pm-pay-km').checked,pay_services:root.querySelector('#pm-pay-services').checked,pay_presentismo:root.querySelector('#pm-pay-presentismo').checked,bonuses:[...root.querySelectorAll('[data-bonus]')].map(r=>({name:r.querySelector('[data-name]').value,amount:r.querySelector('[data-amount]').value})),commissions:[...root.querySelectorAll('[data-commission]')].map(r=>({concept_id:r.querySelector('[data-concept]').value,name:r.querySelector('[data-concept]').selectedOptions[0]?.textContent,source:r.querySelector('[data-source]').value,mode:r.querySelector('[data-mode]').value,value:r.querySelector('[data-value]').value}))});}
function receiptHtml(liq){const m=liq.compensation_snapshot;if(!m?.km_basis)return '';return '<div class="pm-help"><b>Detalle de la matriz</b><div>Base KM: '+(m.km_basis==='billed'?'facturados':'reales')+'</div>'+(m.bonuses||[]).map(b=>'<div>'+esc(b.name)+' · $'+Number(b.amount).toLocaleString('es-AR')+'</div>').join('')+(m.commission_details||[]).map(c=>'<div>'+esc(c.name)+' · '+c.base+' × '+c.value+(c.mode==='percent'?'%':' $')+' = $'+Number(c.total).toLocaleString('es-AR')+'</div>').join('')+'</div>';}
function journeyKm(j){if(j.status!=='closed')return null;if(j.km_inicio==null||j.km_final==null||!Number.isFinite(Number(j.km_inicio))||!Number.isFinite(Number(j.km_final))||Number(j.km_final)<Number(j.km_inicio))throw Error('Jornada con odómetros incompletos o inválidos. Corregila antes de liquidar.');return Number(j.km_final)-Number(j.km_inicio);}
window.PayrollMatrix={journeyKm,normalize,calculate,open,read,receiptHtml,addBonus:b=>document.getElementById('pm-bonuses').insertAdjacentHTML('beforeend',bonusRow(b)),addCommission:()=>document.getElementById('pm-commissions').insertAdjacentHTML('beforeend',commissionRow())};
})();
