/* Salary matrix: explicit bases, recurring bonuses and concept commissions. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>{const raw=String(v??'').trim();const n=Number(raw.includes(',')?raw.replace(/\./g,'').replace(',','.'): /^\d{1,3}(\.\d{3})+$/.test(raw)?raw.replace(/\./g,''):raw);if(!Number.isFinite(n)||n<0)throw Error('Ingresá importes válidos y positivos.');return n;};
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
let commissionCatalog=[],openId=0;
const PAY_TYPES=['fixed','fixed_plus','variable'];
const PAY_TYPE_LABELS={fixed:'Fija',fixed_plus:'Fija + servicios',variable:'Por servicios y km'};
/* Tipo de remuneración guardado; si falta se deduce de las banderas y del sueldo fijo. */
function payType(matrix,basico){const x=matrix||{};if(PAY_TYPES.includes(x.pay_type))return x.pay_type;if(x.pay_services===false&&x.pay_km===false)return 'fixed';return Number(basico)>0?'fixed_plus':'variable';}
function normalize(value){const x=value||{};if(!['real','billed'].includes(x.km_basis||'real'))throw Error('Base de kilómetros inválida.');const bonuses=(x.bonuses||[]).map(b=>({name:String(b.name||'').trim(),amount:money(b.amount)}));if(bonuses.some(b=>!b.name))throw Error('Nombrá cada bono mensual.');const seen=new Set();const commissions=(x.commissions||[]).map(c=>{if((!c.concept_id&&c.source!=='captacion')||!['extras','invoices','captacion'].includes(c.source)||!['fixed','percent'].includes(c.mode))throw Error('Completá concepto, origen y modalidad de la comisión.');const value=money(c.value);if(c.mode==='percent'&&value>100)throw Error('El porcentaje no puede superar 100.');const key=c.source+':'+c.concept_id;if(seen.has(key))throw Error('El concepto tiene dos reglas para el mismo origen.');seen.add(key);return{commission_id:c.commission_id||null,concept_id:c.source==='captacion'?null:c.concept_id,name:c.name||'',source:c.source,mode:c.mode,value};});const pay_type=PAY_TYPES.includes(x.pay_type)?x.pay_type:null;const fixed=pay_type==='fixed';return{...(pay_type?{pay_type}:{}),km_basis:x.km_basis||'real',pay_km:!fixed&&x.pay_km!==false,pay_services:!fixed&&x.pay_services!==false,pay_presentismo:x.pay_presentismo!==false,bonuses,commissions};}
function calculate(matrix,sources,realKm){const m=normalize(matrix);const billedRows=[...new Map((sources.invoices||[]).filter(r=>r.km!=null).map(r=>[r.id??r,r])).values()];const km=m.km_basis==='billed'?round(billedRows.reduce((sum,r)=>sum+money(r.km),0)):money(realKm);const details=m.commissions.map(rule=>{const matching=(sources[rule.source]||[]).filter(r=>rule.source==='captacion'||r.concept_id===rule.concept_id);const rows=[...new Map(matching.map(r=>[r.id??r,r])).values()];if(rule.mode==='percent'&&rows.some(r=>r.currency!=='ARS'))throw Error('La comisión porcentual requiere importes en ARS.');const base=rows.reduce((s,r)=>s+money(rule.mode==='fixed'?r.quantity:r.amount),0);return{...rule,base,total:round(base*rule.value/(rule.mode==='percent'?100:1)),records:rows.map(r=>r.id),record_details:rows.map(r=>({id:r.id,service_id:r.service_id,remito_id:r.remito_id,amount:r.amount,quantity:r.quantity,total:round(money(rule.mode==='fixed'?r.quantity:r.amount)*rule.value/(rule.mode==='percent'?100:1))}))};});return{km,bonus:round(m.bonuses.reduce((s,b)=>s+b.amount,0)),commission:round(details.reduce((s,c)=>s+c.total,0)),snapshot:{...m,commission_details:details,km_records:m.km_basis==='billed'?billedRows.map(r=>r.id):[],km}};}
function commissionSourceLabel(source){return source==='invoices'?'Servicio principal':source==='captacion'?'Captación de particular':'Venta / adicional';}
function commissionFormula(c){return c.source==='captacion'?(c.mode==='percent'?c.value+'% de lo cobrado':'$'+Number(c.value).toLocaleString('es-AR')+' por servicio'):c.mode==='percent'?c.value+'% del importe':'$'+Number(c.value).toLocaleString('es-AR')+' por unidad';}
function bonusRow(b={}){return `<div data-bonus class="pm-row"><input class="form-input" data-name placeholder="Nombre: desempeño, otro…" value="${esc(b.name||'')}"><input class="form-input" data-amount inputmode="decimal" placeholder="Importe mensual" value="${esc(b.amount??'')}"><button type="button" class="pm-row-remove" onclick="this.parentElement.remove()" aria-label="Quitar bono">×</button></div>`;}
function commissionAssignmentRow(c,selected){const formula=commissionFormula(c);const source=commissionSourceLabel(c.source);return `<label class="ax-switch pm-switch"><span class="pm-switch-text"><b>${esc(c.name)}</b><small>${esc(source)} · ${esc(formula)}</small></span><input type="checkbox" data-commission-id="${esc(c.commission_id)}" ${selected?'checked':''}></label>`;}
function moneyField(id,label,value,hint){return `<label class="pm-field"><span>${label}</span><span class="pm-money"><i>$</i><input class="form-input" id="${id}" type="number" step="0.01" min="0" placeholder="0" value="${esc(value??'')}"></span>${hint?`<small>${hint}</small>`:''}</label>`;}
function switchRow(id,title,help,checked){return `<label class="ax-switch pm-switch"><span class="pm-switch-text"><b>${title}</b><small>${help}</small></span><input type="checkbox" id="${id}" ${checked?'checked':''}></label>`;}
const TYPE_HELP={fixed:'Solo sueldo fijo mensual.',fixed_plus:'Sueldo fijo más pago por servicio y/o km.',variable:'Sin fijo: se paga por servicio y/o km.'};
/* Arma las tres columnas del esquema: tipo, matriz y bonos/comisiones. */
async function open(matrix,values={}){const requestId=++openId;let root=document.getElementById('payroll-matrix-fields');if(!root){root=document.createElement('div');root.id='payroll-matrix-fields';document.querySelector('#modal-esquema-edit .modal-body').appendChild(root);}root.className='pm-grid';root.innerHTML='<p class="pm-help">Cargando esquema…</p>';await Promise.resolve();if(requestId!==openId)return;const m=normalize(matrix);const type=payType(matrix,values.sueldo_basico);const selected=new Set(m.commissions.map(c=>c.commission_id).filter(Boolean));const active=commissionCatalog.filter(c=>c.active!==false);
root.dataset.type=type;
root.innerHTML=`<section class="pm-col pm-col-type"><h3><span></span>Tipo de remuneración</h3><div class="pm-types" role="radiogroup" aria-label="Tipo de remuneración">${PAY_TYPES.map(t=>`<button type="button" role="radio" data-pay-type="${t}" aria-checked="${t===type}" onclick="PayrollMatrix.setType('${t}')"><b>${PAY_TYPE_LABELS[t]}</b><small>${TYPE_HELP[t]}</small></button>`).join('')}</div><div class="pm-basico">${moneyField('esq-basico','Sueldo fijo mensual',values.sueldo_basico)}</div></section>
<section class="pm-col pm-col-matrix"><h3><span></span>Matriz de remuneración</h3><div class="pm-block">${switchRow('pm-pay-services','Pago por servicio','Importe por cada remito firmado.',m.pay_services)}<div class="pm-sub" data-for="pm-pay-services">${moneyField('esq-valor-serv','Valor por servicio',values.valor_servicio)}</div></div><div class="pm-block">${switchRow('pm-pay-km','Pago por kilómetro','Elegí qué kilómetros se liquidan.',m.pay_km)}<div class="pm-sub" data-for="pm-pay-km">${moneyField('esq-valor-km','Valor por km',values.valor_km)}<input type="hidden" id="pm-km" value="${m.km_basis}"><div class="ax-seg pm-seg" role="group" aria-label="Kilómetros a liquidar"><button type="button" data-km="real" aria-pressed="${m.km_basis==='real'}" onclick="PayrollMatrix.setKm('real')">KM reales</button><button type="button" data-km="billed" aria-pressed="${m.km_basis==='billed'}" onclick="PayrollMatrix.setKm('billed')">KM facturados</button></div><small class="pm-help" id="pm-km-help">${m.km_basis==='billed'?'Los km cobrados en los servicios facturados.':'Odómetro final menos inicial de cada jornada.'}</small></div></div></section>
<section class="pm-col pm-col-extras"><h3><span></span>Bonos y comisiones</h3><div class="pm-block">${switchRow('pm-pay-presentismo','Presentismo','Se paga si tuvo jornadas y no registró incidentes.',m.pay_presentismo)}<div class="pm-sub" data-for="pm-pay-presentismo">${moneyField('esq-bono-pres','Importe mensual',values.bono_presentismo)}</div></div><div class="pm-block"><div class="pm-block-head"><b>Bonos mensuales</b><button type="button" class="pm-link" onclick="PayrollMatrix.addBonus()">+ Bono</button></div><div id="pm-bonuses">${m.bonuses.map(bonusRow).join('')}</div></div><div class="pm-block"><div class="pm-block-head"><b>Comisiones</b></div><div id="pm-commissions" class="pm-switch-list">${active.map(c=>commissionAssignmentRow(c,selected.has(c.commission_id))).join('')||'<p class="pm-help">Todavía no hay comisiones activas.</p>'}</div></div></section>`;
root.querySelectorAll('#pm-pay-services,#pm-pay-km,#pm-pay-presentismo').forEach(el=>{el.onchange=()=>syncSubs(root);});syncSubs(root);}
function syncSubs(root){root.querySelectorAll('.pm-sub[data-for]').forEach(sub=>{const on=!!root.querySelector('#'+sub.dataset.for)?.checked;sub.classList.toggle('is-off',!on);sub.querySelectorAll('input,button').forEach(el=>{el.disabled=!on;});});}
function setType(type){const root=document.getElementById('payroll-matrix-fields');if(!root||!PAY_TYPES.includes(type))return;root.dataset.type=type;root.querySelectorAll('[data-pay-type]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.payType===type)));}
function setKm(basis){const root=document.getElementById('payroll-matrix-fields');if(!root)return;root.querySelector('#pm-km').value=basis;root.querySelectorAll('[data-km]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.km===basis)));const help=root.querySelector('#pm-km-help');if(help)help.textContent=basis==='billed'?'Los km cobrados en los servicios facturados.':'Odómetro final menos inicial de cada jornada.';}
function read(){const root=document.getElementById('payroll-matrix-fields');if(!root?.querySelector('#pm-km'))throw Error('Esperá a que cargue el esquema.');const type=PAY_TYPES.includes(root.dataset.type)?root.dataset.type:'fixed_plus';const selected=new Set([...root.querySelectorAll('[data-commission-id]:checked')].map(el=>el.dataset.commissionId));const fixed=type==='fixed';const out=normalize({pay_type:type,km_basis:root.querySelector('#pm-km').value,pay_km:!fixed&&root.querySelector('#pm-pay-km').checked,pay_services:!fixed&&root.querySelector('#pm-pay-services').checked,pay_presentismo:root.querySelector('#pm-pay-presentismo').checked,bonuses:[...root.querySelectorAll('[data-bonus]')].map(r=>({name:r.querySelector('[data-name]').value,amount:r.querySelector('[data-amount]').value})).filter(b=>String(b.name).trim()||String(b.amount).trim()),commissions:commissionCatalog.filter(c=>selected.has(c.commission_id))});if(type==='variable'&&!out.pay_services&&!out.pay_km)throw Error('Con "Por servicios y km" activá el pago por servicio o por km.');return out;}
function receiptHtml(liq){const m=liq.compensation_snapshot;if(!m?.km_basis)return '';return '<div class="pm-help"><b>Detalle de la matriz</b><div>Base KM: '+(m.km_basis==='billed'?'facturados':'reales')+'</div>'+(m.bonuses||[]).map(b=>'<div>'+esc(b.name)+' · $'+Number(b.amount).toLocaleString('es-AR')+'</div>').join('')+(m.commission_details||[]).map(c=>'<div>'+esc(c.name)+' · '+c.base+' × '+c.value+(c.mode==='percent'?'%':' $')+' = $'+Number(c.total).toLocaleString('es-AR')+'</div>').join('')+'</div>';}
function journeyKm(j){if(j.status!=='closed')return null;if(j.km_inicio==null||j.km_final==null||!Number.isFinite(Number(j.km_inicio))||!Number.isFinite(Number(j.km_final))||Number(j.km_final)<Number(j.km_inicio))throw Error('Jornada con odómetros incompletos o inválidos. Corregila antes de liquidar.');return Number(j.km_final)-Number(j.km_inicio);}
window.PayrollMatrix={journeyKm,normalize,calculate,commissionSourceLabel,commissionFormula,payType,PAY_TYPE_LABELS,open,read,setType,setKm,receiptHtml,setCommissionCatalog:rules=>{commissionCatalog=Array.isArray(rules)?rules:[];},addBonus:b=>document.getElementById('pm-bonuses').insertAdjacentHTML('beforeend',bonusRow(b))};
})();
